FROM node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM node:18-alpine
WORKDIR /app
RUN npm install -g http-server
COPY --from=build /app/dist /app/dist
ENV NODE_ENV=production
EXPOSE 8080
CMD ["http-server", "dist", "-p", "8080", "-c-1"]
