"""API router for dependencies.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)
from socialseed_tasker.entrypoints.web_api.routers.policy import _policy_engine

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Dependencies router
# ---------------------------------------------------------------------------

dependencies_router = APIRouter()


@dependencies_router.post(
    "/issues/{issue_id}/dependencies",
    response_model=APIResponse[DependencyResponse],
    status_code=201,
    summary="Add a dependency",
    description=("Create a [:DEPENDS_ON] relationship. Fails if adding it would create a circular dependency."),
    responses={
        404: {"description": "Issue not found"},
        409: {"description": "Circular dependency detected"},
    },
)
def add_dependency(
    issue_id: str,
    body: DependencyRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
    request: Request = None,
):
    from socialseed_tasker.core.project_analysis.policy import PolicyEngine
    from socialseed_tasker.core.task_management.actions import PolicyViolationError

    policies = _policy_engine.get("policies", [])
    if policies and request and hasattr(request.app.state, "config"):
        enforcement_mode = getattr(request.app.state.config, "policy_enforcement_mode", "warn")

        if enforcement_mode != "disabled":
            engine = PolicyEngine(policies)

            issue = repo.get_issue(issue_id)
            target = repo.get_issue(body.depends_on_id)

            if issue and target:
                from_component = repo.get_component(str(issue.component_id))
                to_component = repo.get_component(str(target.component_id))

                result = engine.validate_dependency(
                    from_component_name=from_component.name if from_component else "",
                    from_component_type=from_component.project if from_component else "",
                    from_labels=issue.labels,
                    to_component_name=to_component.name if to_component else "",
                    to_component_type=to_component.project if to_component else "",
                    to_labels=target.labels,
                )

                if result.has_violations and enforcement_mode == "block":
                    violation = result.violations[0]
                    raise PolicyViolationError(
                        policy_name=violation.policy_name,
                        rule_type=violation.rule_type.value,
                        message=violation.message,
                        suggestion=violation.suggestion,
                    )

    add_dependency_action(repo, issue_id, body.depends_on_id)
    return APIResponse(
        data=DependencyResponse(issue_id=issue_id, depends_on_id=body.depends_on_id),
        meta=Meta(request_id=None),
    )


@dependencies_router.post(
    "/issues/{issue_id}/dependencies/bulk",
    response_model=APIResponse[BulkDependencyResponse],
    summary="Add multiple dependencies",
    description="Add multiple [:DEPENDS_ON] relationships in a single request.",
    responses={
        404: {"description": "Issue not found"},
        409: {"description": "Circular dependency detected"},
    },
)
def add_dependencies_bulk(
    issue_id: str,
    body: BulkDependencyRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    from socialseed_tasker.core.task_management.actions import (
        CircularDependencyError,
        IssueNotFoundError,
    )

    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    successful = 0
    failed = 0
    results = []

    for dep_id in body.depends_on_ids:
        try:
            add_dependency_action(repo, issue_id, dep_id)
            successful += 1
            results.append({"depends_on_id": dep_id, "status": "created"})
        except IssueNotFoundError:
            failed += 1
            results.append({"depends_on_id": dep_id, "status": "error", "message": "Target issue not found"})
        except CircularDependencyError as e:
            failed += 1
            results.append({"depends_on_id": dep_id, "status": "error", "message": str(e)})
        except Exception as e:
            failed += 1
            results.append({"depends_on_id": dep_id, "status": "error", "message": str(e)})

    return APIResponse(
        data=BulkDependencyResponse(
            issue_id=issue_id,
            total_requested=len(body.depends_on_ids),
            successful=successful,
            failed=failed,
            results=results,
        ),
        meta=Meta(request_id=None),
    )


@dependencies_router.delete(
    "/issues/{issue_id}/dependencies/{depends_on_id}",
    status_code=204,
    summary="Remove a dependency",
    description="Remove a [:DEPENDS_ON] relationship between two issues.",
    responses={404: {"description": "Issue not found"}},
)
def remove_dependency(
    issue_id: str,
    depends_on_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    remove_dependency_action(repo, issue_id, depends_on_id)


@dependencies_router.get(
    "/issues/{issue_id}/dependencies",
    response_model=APIResponse[PaginatedResponse[IssueResponse]],
    summary="List dependencies",
    description="List all issues that this issue depends on.",
)
def list_dependencies(
    issue_id: str,
    page: int = Query(1, ge=1, description="Page number (starts at 1, default: 1)"),
    limit: int = Query(20, ge=1, le=100, description="Items per page (default: 20, max: 100)"),
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    deps = repo.get_dependencies(issue_id)
    total = len(deps)
    start = (page - 1) * limit
    end = start + limit
    page_items = deps[start:end]
    return APIResponse(
        data=_paginated([_issue_to_response(d) for d in page_items], page, limit, total),
        meta=Meta(request_id=None),
    )


@dependencies_router.get(
    "/issues/{issue_id}/dependents",
    response_model=APIResponse[list[IssueResponse]],
    summary="List dependents",
    description="List all issues that depend on this issue.",
)
def list_dependents(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    dependents = repo.get_dependents(issue_id)
    return APIResponse(data=[_issue_to_response(d) for d in dependents], meta=Meta(request_id=None))


@dependencies_router.get(
    "/issues/{issue_id}/dependency-chain",
    response_model=APIResponse[list[IssueResponse]],
    summary="Get dependency chain",
    description="Get the full transitive dependency chain for an issue.",
)
def get_dependency_chain(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    chain = get_dependency_chain_action(repo, issue_id)
    return APIResponse(data=[_issue_to_response(i) for i in chain], meta=Meta(request_id=None))


@dependencies_router.get(
    "/blocked-issues",
    response_model=APIResponse[list[IssueResponse]],
    summary="List blocked issues",
    description="List all issues blocked by at least one open dependency.",
)
def list_blocked_issues(
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    blocked = get_blocked_issues_action(repo)
    return APIResponse(data=[_issue_to_response(i) for i in blocked], meta=Meta(request_id=None))


@dependencies_router.get(
    "/workable-issues",
    response_model=APIResponse[list[IssueResponse]],
    summary="List workable issues",
    description=(
        "List all issues that are ready to work on. "
        "An issue is workable if its status is not CLOSED and all its dependencies are CLOSED. "
        "Supports filtering by priority and component."
    ),
)
def list_workable_issues(
    priority: str | None = Query(None, description="Filter by priority (HIGH, MEDIUM, LOW)"),
    component: str | None = Query(None, description="Filter by component ID"),
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    workable = get_workable_issues_action(repo, priority=priority, component_id=component)
    return APIResponse(data=[_issue_to_response(i) for i in workable], meta=Meta(request_id=None))


# ---------------------------------------------------------------------------
# CodeSymbol AFFECTS relationships
# ---------------------------------------------------------------------------


@dependencies_router.post(
    "/issues/{issue_id}/affects",
    response_model=APIResponse[dict],
    summary="Link CodeSymbol to Issue",
    description="Create an AFFECTS relationship between an Issue and a CodeSymbol.",
)
def add_affects_symbol(
    issue_id: str,
    symbol_id: str = Body(..., description="The CodeSymbol ID to link"),
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    repo.add_affects_symbol(issue_id, symbol_id)
    return APIResponse(data={"status": "linked", "issue_id": issue_id, "symbol_id": symbol_id}, meta=Meta(request_id=None))


@dependencies_router.get(
    "/issues/{issue_id}/affects",
    response_model=APIResponse[list[dict]],
    summary="Get affected CodeSymbols",
    description="Get all CodeSymbols affected by an Issue.",
)
def get_affected_symbols(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    symbols = repo.get_affected_symbols(issue_id)
    return APIResponse(data=symbols, meta=Meta(request_id=None))


@dependencies_router.delete(
    "/issues/{issue_id}/affects",
    response_model=APIResponse[dict],
    summary="Remove CodeSymbol from Issue",
    description="Remove an AFFECTS relationship between an Issue and a CodeSymbol.",
)
def remove_affects_symbol(
    issue_id: str,
    symbol_id: str = Body(..., description="The CodeSymbol ID to unlink"),
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    repo.remove_affects_symbol(issue_id, symbol_id)
    return APIResponse(data={"status": "unlinked", "issue_id": issue_id, "symbol_id": symbol_id}, meta=Meta(request_id=None))


@dependencies_router.get(
    "/code/symbols/{symbol_id}/issues",
    response_model=APIResponse[list[IssueResponse]],
    summary="Get issues affecting CodeSymbol",
    description="Get all Issues that affect a specific CodeSymbol.",
)
def get_issues_affecting_symbol(
    symbol_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issues = repo.get_issues_affecting_symbol(symbol_id)
    return APIResponse(data=[_issue_to_response(i) for i in issues], meta=Meta(request_id=None))
