"""API router for policy_relationships.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Policy Relationships Router
# ---------------------------------------------------------------------------

policy_rel_router = APIRouter()


def _policy_to_response(policy: "Policy") -> "PolicyResponse":  # type: ignore[valid-type]
    """Convert domain Policy to API response."""
    return PolicyResponse(
        id=str(policy.id),
        name=policy.name,
        description=policy.description,
        rules=[r.model_dump() for r in policy.rules],
        target_scope=policy.target_scope.value,
        logic_definition=policy.logic_definition,
        remediation_strategy=policy.remediation_strategy,
        autofix_template=policy.autofix_template,
        is_active=policy.is_active,
        created_at=policy.created_at,
        updated_at=policy.updated_at,
    )


@policy_rel_router.post(
    "/policies/{policy_id}/link/project/{project_id}",
    response_model=APIResponse[dict],
    summary="Link policy to project",
    description="Create (Project)-[:ENFORCES]->(Policy) relationship.",
)
def link_policy_to_project(
    policy_id: str,
    project_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Link policy to a project."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository

    repo = PolicyRepository(driver)
    repo.link_policy_to_project(policy_id, project_id)

    return APIResponse(data={"status": "linked"}, meta=Meta(request_id=None))


@policy_rel_router.post(
    "/policies/{policy_id}/link/agent/{agent_id}",
    response_model=APIResponse[dict],
    summary="Link policy to agent",
    description="Create (Agent)-[:MUST_COMPLY_WITH]->(Policy) relationship.",
)
def link_policy_to_agent(
    policy_id: str,
    agent_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Link policy to an agent."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository

    repo = PolicyRepository(driver)
    repo.link_policy_to_agent(policy_id, agent_id)

    return APIResponse(data={"status": "linked"}, meta=Meta(request_id=None))


@policy_rel_router.post(
    "/policies/{policy_id}/link/component/{component_id}",
    response_model=APIResponse[dict],
    summary="Link policy to component",
    description="Create (Policy)-[:APPLIES_TO]->(Component) relationship.",
)
def link_policy_to_component(
    policy_id: str,
    component_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Link policy to a component."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository

    repo = PolicyRepository(driver)
    repo.link_policy_to_component(policy_id, component_id)

    return APIResponse(data={"status": "linked"}, meta=Meta(request_id=None))


@policy_rel_router.get(
    "/policies/project/{project_id}",
    response_model=APIResponse[list[PolicyResponse]],
    summary="Get policies for project",
    description="Get all policies enforced by a project.",
)
def get_policies_for_project(
    project_id: str,
    limit: int = Query(50, ge=1, le=100),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[list[PolicyResponse]]:
    """Get policies for a project."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository

    repo = PolicyRepository(driver)
    policies = repo.get_policies_for_project(project_id, limit=limit)

    return APIResponse(
        data=[_policy_to_response(p) for p in policies],
        meta=Meta(request_id=None),
    )


@policy_rel_router.get(
    "/policies/agent/{agent_id}",
    response_model=APIResponse[list[PolicyResponse]],
    summary="Get policies for agent",
    description="Get all policies an agent must comply with.",
)
def get_policies_for_agent(
    agent_id: str,
    limit: int = Query(50, ge=1, le=100),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[list[PolicyResponse]]:
    """Get policies for an agent."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository

    repo = PolicyRepository(driver)
    policies = repo.get_policies_for_agent(agent_id, limit=limit)

    return APIResponse(
        data=[_policy_to_response(p) for p in policies],
        meta=Meta(request_id=None),
    )


@policy_rel_router.get(
    "/policies/component/{component_id}",
    response_model=APIResponse[list[PolicyResponse]],
    summary="Get policies for component",
    description="Get all policies that apply to a component.",
)
def get_policies_for_component(
    component_id: str,
    limit: int = Query(50, ge=1, le=100),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[list[PolicyResponse]]:
    """Get policies for a component."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository

    repo = PolicyRepository(driver)
    policies = repo.get_policies_for_component(component_id, limit=limit)

    return APIResponse(
        data=[_policy_to_response(p) for p in policies],
        meta=Meta(request_id=None),
    )
