from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class DualModeConfig:
    """CLI mode configuration — determines how the CLI connects to the backend.

    Resolution order:
    1. Environment variables (``TASKER_MODE``, ``TASKER_API_URL``, …)
    2. ``TASKER_CONFIG_PATH`` env var (explicit path to a config file)
    3. ``.agent/configs/tasker.yml`` (generated by ``tasker init``, discovered from CWD upward)
    4. Built-in defaults (mode = ``direct``)
    """

    mode: str = "direct"
    api_url: str = "http://localhost:8888"
    api_key: str = ""
    api_timeout: int = 30
    neo4j_uri: str = "bolt://localhost:7687"
    neo4j_user: str = "neo4j"
    neo4j_password: str = ""

    @classmethod
    def load(cls, config_path: str | Path | None = None) -> DualModeConfig:
        """Load config from env vars, falling back to YAML file then defaults."""
        if config_path is None:
            config_path = _discover_config_file()
        file_cfg = _read_yaml_file(config_path) if config_path else {}

        mode = (
            os.environ.get("TASKER_MODE")
            or file_cfg.get("mode")
            or "direct"
        )
        api_url = (
            os.environ.get("TASKER_API_URL")
            or file_cfg.get("api_url")
            or "http://localhost:8888"
        )
        api_key = (
            os.environ.get("TASKER_API_KEY")
            or file_cfg.get("api_key")
            or ""
        )
        api_timeout = int(
            os.environ.get("TASKER_API_TIMEOUT")
            or file_cfg.get("api_timeout", 30)
        )
        neo4j_uri = (
            os.environ.get("TASKER_NEO4J_URI")
            or file_cfg.get("neo4j_uri")
            or "bolt://localhost:7687"
        )
        neo4j_user = (
            os.environ.get("TASKER_NEO4J_USER")
            or file_cfg.get("neo4j_user")
            or "neo4j"
        )
        neo4j_password = (
            os.environ.get("TASKER_NEO4J_PASSWORD")
            or file_cfg.get("neo4j_password")
            or ""
        )

        return cls(
            mode=mode,
            api_url=api_url,
            api_key=api_key,
            api_timeout=api_timeout,
            neo4j_uri=neo4j_uri,
            neo4j_user=neo4j_user,
            neo4j_password=neo4j_password,
        )


def _discover_config_file() -> Path | None:
    """Search upward from cwd for ``.agent/configs/tasker.yml``.

    Resolution order:
    1. ``TASKER_CONFIG_PATH`` env var (if set and file exists)
    2. ``.agent/configs/tasker.yml`` relative to CWD
    3. ``.agent/configs/tasker.yml`` in each parent directory upward
    """
    explicit = os.environ.get("TASKER_CONFIG_PATH")
    if explicit:
        candidate = Path(explicit)
        if candidate.exists():
            return candidate.resolve()
    cwd = Path.cwd()
    for parent in [cwd] + list(cwd.parents):
        candidate = parent / ".agent" / "configs" / "tasker.yml"
        if candidate.exists():
            return candidate
    return None


def _read_yaml_file(config_path: str | Path) -> dict[str, Any]:
    path = Path(config_path)
    if not path.exists():
        return {}
    try:
        import yaml
        with open(path) as f:
            data = yaml.safe_load(f)
            return data if isinstance(data, dict) else {}
    except Exception:
        return {}
