"""FastAPI routers package exposing all individual routers for backward compatibility."""

from socialseed_tasker.infrastructure.web_api.routers.issues import issues_router
from socialseed_tasker.infrastructure.web_api.routers.dependencies import dependencies_router
from socialseed_tasker.infrastructure.web_api.routers.components import components_router
from socialseed_tasker.infrastructure.web_api.routers.components_dependencies import components_dep_router
from socialseed_tasker.infrastructure.web_api.routers.labels import label_router
from socialseed_tasker.infrastructure.web_api.routers.analysis import analysis_router
from socialseed_tasker.infrastructure.web_api.routers.cost_analytics import cost_analytics_router
from socialseed_tasker.infrastructure.web_api.routers.ai_search import ai_search_router
from socialseed_tasker.infrastructure.web_api.routers.policy import policy_router
from socialseed_tasker.infrastructure.web_api.routers.policy_relationships import policy_rel_router
from socialseed_tasker.infrastructure.web_api.routers.user import user_router
from socialseed_tasker.infrastructure.web_api.routers.commit import commit_router
from socialseed_tasker.infrastructure.web_api.routers.project import project_router
from socialseed_tasker.infrastructure.web_api.routers.webhook import webhook_router
from socialseed_tasker.infrastructure.web_api.routers.agent import agent_router
from socialseed_tasker.infrastructure.web_api.routers.admin import admin_router
from socialseed_tasker.infrastructure.web_api.routers.sync import sync_router
from socialseed_tasker.infrastructure.web_api.routers.constraints import constraints_router
from socialseed_tasker.infrastructure.web_api.routers.epic import epic_router
from socialseed_tasker.infrastructure.web_api.routers.objective import objective_router
from socialseed_tasker.infrastructure.web_api.routers.code_graph import code_graph_router
from socialseed_tasker.infrastructure.web_api.routers.rag import rag_router
from socialseed_tasker.infrastructure.web_api.routers.reasoning import reasoning_router
from socialseed_tasker.infrastructure.web_api.routers.tenants import tenants_router
