"""API router for agent.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# In-memory fallback store for agents (used when Neo4j is unavailable)
_agents: dict[str, Any] = {}

# ---------------------------------------------------------------------------
# Agent router
# ---------------------------------------------------------------------------

agent_router = APIRouter()


@agent_router.post(
    "/agents/register",
    response_model=APIResponse[AgentResponse],
    status_code=201,
    summary="Register an agent",
    description="Register a new agent in the swarm coordination system.",
)
def register_agent(
    request: Request,
    body: AgentRegisterRequest,
) -> APIResponse[AgentResponse]:
    from datetime import datetime, timezone
    from fastapi import HTTPException
    from socialseed_tasker.infrastructure import neo4j_queries

    agent_data = {
        "agent_id": body.agent_id,
        "name": body.name,
        "role": body.role,
        "status": "idle",
        "current_issue_id": None,
        "capabilities": body.capabilities,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "last_heartbeat": datetime.now(timezone.utc).isoformat(),
    }
    _agents[body.agent_id] = agent_data

    driver = getattr(request.app.state, "driver", None)
    if driver is None:
        try:
            from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
            driver = get_neo4j_driver()
        except Exception:
            driver = None
    
    assigned_project_id = body.project_id
    
    if driver is not None:
        actual_driver = driver.driver if hasattr(driver, "driver") else driver
        db = driver.database if hasattr(driver, "database") else "neo4j"
        with actual_driver.session(database=db) as session:
            session.run(
                neo4j_queries.CREATE_AGENT_NODE,
                id=body.agent_id,
                name=body.name,
                role=body.role,
                status="idle",
                capabilities=", ".join(body.capabilities) if body.capabilities else "",
                createdAt=agent_data["created_at"],
            )
            
            project_id_to_assign = assigned_project_id
            
            if not project_id_to_assign:
                result = session.run(neo4j_queries.LIST_PROJECT_NODES)
                projects = list(result)
                if len(projects) == 1:
                    sole_project = projects[0]["p"]
                    project_id_to_assign = sole_project.get("id") or sole_project.get("slug")
                elif len(projects) > 1:
                    project_id_to_assign = projects[0]["p"].get("id") or projects[0]["p"].get("slug")
            
            if project_id_to_assign:
                session.run(
                    neo4j_queries.PROJECT_ASSIGN_AGENT,
                    projectId=project_id_to_assign,
                    agentId=body.agent_id,
                )
                assigned_project_id = project_id_to_assign

    return APIResponse(
        data=AgentResponse(
            agent_id=body.agent_id,
            name=body.name,
            role=body.role,
            status="idle",
            current_issue_id=None,
            capabilities=body.capabilities,
            created_at=agent_data["created_at"],
            last_heartbeat=agent_data["last_heartbeat"],
            project_id=assigned_project_id,
        ),
        meta=Meta(request_id=None),
    )


@agent_router.get(
    "/agents",
    response_model=APIResponse[list[AgentResponse]],
    summary="List agents",
    description="List all registered agents.",
)
def list_agents() -> APIResponse[list[AgentResponse]]:

    agents = []
    for agent_data in _agents.values():
        agents.append(
            AgentResponse(
                agent_id=agent_data["agent_id"],
                name=agent_data["name"],
                role=agent_data["role"],
                status=agent_data["status"],
                current_issue_id=agent_data["current_issue_id"],
                capabilities=agent_data["capabilities"],
                created_at=agent_data["created_at"],
                last_heartbeat=agent_data["last_heartbeat"],
            )
        )
    return APIResponse(data=agents, meta=Meta(request_id=None))


@agent_router.get(
    "/agents/{agent_id}",
    response_model=APIResponse[AgentResponse],
    summary="Get agent",
    description="Get details of a specific agent.",
)
def get_agent(agent_id: str) -> APIResponse[AgentResponse]:

    if agent_id not in _agents:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")

    agent_data = _agents[agent_id]
    return APIResponse(
        data=AgentResponse(
            agent_id=agent_data["agent_id"],
            name=agent_data["name"],
            role=agent_data["role"],
            status=agent_data["status"],
            current_issue_id=agent_data["current_issue_id"],
            capabilities=agent_data["capabilities"],
            created_at=agent_data["created_at"],
            last_heartbeat=agent_data["last_heartbeat"],
        ),
        meta=Meta(request_id=None),
    )


@agent_router.post(
    "/agents/{agent_id}/heartbeat",
    response_model=APIResponse[AgentResponse],
    summary="Agent heartbeat",
    description="Update agent heartbeat and status.",
)
def agent_heartbeat(
    agent_id: str,
    body: AgentUpdateRequest,
) -> APIResponse[AgentResponse]:
    from datetime import datetime, timezone

    if agent_id not in _agents:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")

    agent_data = _agents[agent_id]
    if body.status:
        agent_data["status"] = body.status
    if body.current_issue_id is not None:
        agent_data["current_issue_id"] = body.current_issue_id
    agent_data["last_heartbeat"] = datetime.now(timezone.utc).isoformat()

    return APIResponse(
        data=AgentResponse(
            agent_id=agent_data["agent_id"],
            name=agent_data["name"],
            role=agent_data["role"],
            status=agent_data["status"],
            current_issue_id=agent_data["current_issue_id"],
            capabilities=agent_data["capabilities"],
            created_at=agent_data["created_at"],
            last_heartbeat=agent_data["last_heartbeat"],
        ),
        meta=Meta(request_id=None),
    )


@agent_router.delete(
    "/agents/{agent_id}",
    response_model=APIResponse[dict],
    summary="Deregister agent",
    description="Deregister an agent from the swarm.",
)
def deregister_agent(agent_id: str) -> APIResponse[dict]:
    if agent_id not in _agents:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")

    del _agents[agent_id]
    return APIResponse(data={"deleted": agent_id}, meta=Meta(request_id=None))


@agent_router.get(
    "/agents/role/{role}",
    response_model=APIResponse[list[AgentResponse]],
    summary="List agents by role",
    description="List all agents with a specific role.",
)
def list_agents_by_role(role: str) -> APIResponse[list[AgentResponse]]:

    agents = []
    for agent_data in _agents.values():
        if agent_data["role"] == role:
            agents.append(
                AgentResponse(
                    agent_id=agent_data["agent_id"],
                    name=agent_data["name"],
                    role=agent_data["role"],
                    status=agent_data["status"],
                    current_issue_id=agent_data["current_issue_id"],
                    capabilities=agent_data["capabilities"],
                    created_at=agent_data["created_at"],
                    last_heartbeat=agent_data["last_heartbeat"],
                )
            )
    return APIResponse(data=agents, meta=Meta(request_id=None))


@agent_router.get(
    "/agent/context/{issue_id}",
    response_model=APIResponse[dict[str, Any]],
    summary="Get code context for issue",
    description="Get code files and symbols relevant to an issue from Code-as-Graph.",
)
def get_agent_context(
    issue_id: str,
    limit: int = Query(20, description="Max files to return"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict[str, Any]]:
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver

    issue = repo.get_issue(issue_id)
    if not issue:
        raise HTTPException(status_code=404, detail=f"Issue '{issue_id}' not found")

    neo4j_driver = get_neo4j_driver()
    if neo4j_driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")

    cg_repo = CodeGraphRepository(neo4j_driver)
    files = cg_repo.get_files(limit=limit)

    return APIResponse(
        data={
            "issue_id": issue_id,
            "issue_title": issue.title,
            "component_id": str(issue.component_id),
            "files": files,
            "count": len(files),
        },
        meta=Meta(request_id=None),
    )


@agent_router.get(
    "/agent/similar/{issue_id}",
    response_model=APIResponse[list[dict[str, Any]]],
    summary="Find similar issues",
    description="Find similar past issues via RAG semantic search.",
)
def get_similar_issues(
    issue_id: str,
    limit: int = Query(5, description="Max similar issues to return"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[dict[str, Any]]]:
    from socialseed_tasker.infrastructure.neo4j_rag_repository import RAGRepository
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver

    issue = repo.get_issue(issue_id)
    if not issue:
        raise HTTPException(status_code=404, detail=f"Issue '{issue_id}' not found")

    neo4j_driver = get_neo4j_driver()
    if neo4j_driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")

    rag_repo = RAGRepository(neo4j_driver)
    results = rag_repo.search(f"issue {issue.title}", limit=limit)

    return APIResponse(
        data=[
            {
                "source_id": r.get("source_id", ""),
                "content": r.get("content", ""),
                "score": r.get("score", 0.0),
            }
            for r in results
        ],
        meta=Meta(request_id=None),
    )


@agent_router.post(
    "/agents/{agent_id}/specialists/{component_id}",
    response_model=APIResponse[dict],
    summary="Add agent specialist in component",
    description="Create (Agent)-[:SPECIALIST_IN]->(Component) relationship.",
)
def add_agent_specialist(
    agent_id: str,
    component_id: str,
) -> APIResponse[dict]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        session.run(
            neo4j_queries.ADD_AGENT_SPECIALIST,
            agent_id=agent_id,
            component_id=component_id,
        )
    return APIResponse(data={"status": "specialist_added"}, meta=Meta(request_id=None))


@agent_router.delete(
    "/agents/{agent_id}/specialists/{component_id}",
    response_model=APIResponse[dict],
    summary="Remove agent specialist",
    description="Remove (Agent)-[:SPECIALIST_IN]->(Component) relationship.",
)
def remove_agent_specialist(
    agent_id: str,
    component_id: str,
) -> APIResponse[dict]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        session.run(
            neo4j_queries.REMOVE_AGENT_SPECIALIST,
            agent_id=agent_id,
            component_id=component_id,
        )
    return APIResponse(data={"status": "specialist_removed"}, meta=Meta(request_id=None))


@agent_router.get(
    "/agents/{agent_id}/specialists",
    response_model=APIResponse[list[dict]],
    summary="Get agent specialists",
    description="Get all components an agent specializes in.",
)
def get_agent_specialists(
    agent_id: str,
) -> APIResponse[list[dict]]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        result = session.run(neo4j_queries.GET_AGENT_SPECIALISTS, agent_id=agent_id)
        components = [dict(r["c"]) for r in result]
    return APIResponse(data=components, meta=Meta(request_id=None))


@agent_router.get(
    "/components/{component_id}/specialists",
    response_model=APIResponse[list[dict]],
    summary="Get component specialists",
    description="Get all agents that specialize in a component.",
)
def get_component_specialists(
    component_id: str,
) -> APIResponse[list[dict]]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        result = session.run(neo4j_queries.GET_COMPONENT_SPECIALISTS, component_id=component_id)
        agents = [dict(r["a"]) for r in result]
    return APIResponse(data=agents, meta=Meta(request_id=None))
