"""API router for ai_search.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    embed_issue_solution,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
    resolve_embedding_port,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    SimilarSolutionsRequest,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# AI Search router
# ---------------------------------------------------------------------------

ai_search_router = APIRouter()


@ai_search_router.get(
    "/search-context",
    response_model=APIResponse[list],
    summary="Semantic search for context",
    description="Search issues by semantic similarity to the query text.",
)
def search_context(
    q: str = Query(..., description="Search query text"),
    threshold: float = Query(0.7, ge=0.0, le=1.0, description="Minimum similarity score"),
    limit: int = Query(10, ge=1, le=50, description="Maximum results"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list]:
    try:
        import os

        openai_api_key = os.environ.get("OPENAI_API_KEY", "")
        if not openai_api_key:
            return APIResponse(
                data=[],
                meta=Meta(request_id=None),
            )
        from openai import OpenAI

        client = OpenAI(api_key=openai_api_key)
        response = client.embeddings.create(
            model="text-embedding-ada-002",
            input=q,
        )
        embedding = response.data[0].embedding
        results = repo.search_by_embedding(embedding, threshold=threshold, limit=limit)
        return APIResponse(data=results, meta=Meta(request_id=None))
    except Exception:
        return APIResponse(data=[], meta=Meta(request_id=None))


@ai_search_router.get(
    "/similar-issues/{issue_id}",
    response_model=APIResponse[list],
    summary="Find similar issues",
    description="Find issues similar to the given issue by semantic similarity.",
)
def find_similar_issues(
    issue_id: str,
    threshold: float = Query(0.7, ge=0.0, le=1.0, description="Minimum similarity score"),
    limit: int = Query(10, ge=1, le=50, description="Maximum results"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list]:
    results = repo.find_similar_issues(issue_id, threshold=threshold, limit=limit)
    return APIResponse(data=results, meta=Meta(request_id=None))


@ai_search_router.post(
    "/issues/{issue_id}/embed",
    response_model=APIResponse[dict],
    summary="Generate embedding for issue",
    description="Generate or regenerate the embedding for an issue description.",
)
def generate_issue_embedding(
    issue_id: str,
    force: bool = Query(False, description="Force regenerate existing embedding"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    try:
        import os

        openai_api_key = os.environ.get("OPENAI_API_KEY", "")
        if not openai_api_key:
            from fastapi import HTTPException

            raise HTTPException(status_code=400, detail="OPENAI_API_KEY not configured")

        issue = repo.get_issue(issue_id)
        if issue is None:
            from fastapi import HTTPException

            raise HTTPException(status_code=404, detail="Issue not found")

        if issue.description_embedding and not force:
            return APIResponse(
                data={"issue_id": issue_id, "embedding_exists": True},
                meta=Meta(request_id=None),
            )

        text = issue.description or issue.title
        from openai import OpenAI

        client = OpenAI(api_key=openai_api_key)
        response = client.embeddings.create(
            model="text-embedding-ada-002",
            input=text,
        )
        embedding = response.data[0].embedding
        repo.update_issue_embedding(issue_id, embedding)

        return APIResponse(
            data={"issue_id": issue_id, "embedding_exists": True},
            meta=Meta(request_id=None),
        )
    except Exception as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=500, detail=str(e))


@ai_search_router.post(
    "/search-similar-solutions",
    response_model=APIResponse[list[Any]],
    summary="Search similar solutions",
    description="Embed the query and return closed issues whose solution embeddings are semantically similar.",
)
def search_similar_solutions(
    body: SimilarSolutionsRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),  # noqa: B008
) -> APIResponse[list[Any]]:
    embedder = resolve_embedding_port()
    if embedder is None:
        return APIResponse(data=[], meta=Meta(request_id=None))
    try:
        query_embedding = embedder.embed_text(body.query)
    except Exception:
        return APIResponse(data=[], meta=Meta(request_id=None))
    if not query_embedding:
        return APIResponse(data=[], meta=Meta(request_id=None))
    candidates = repo.search_by_embedding(
        query_embedding,
        threshold=body.threshold,
        limit=min(body.limit * 3, 50),
    )
    solutions: list[dict[str, Any]] = []
    for candidate in candidates:
        issue = repo.get_issue(str(candidate["issue_id"]))
        if issue is None or issue.status != IssueStatus.CLOSED:
            continue
        solutions.append(
            {
                "issue_id": candidate["issue_id"],
                "title": issue.title,
                "score": candidate.get("score", 0.0),
                "resolution": issue.resolution,
            }
        )
        if len(solutions) >= body.limit:
            break
    return APIResponse(data=solutions, meta=Meta(request_id=None))


@ai_search_router.post(
    "/backfill-embeddings",
    response_model=APIResponse[dict[str, Any]],
    summary="Backfill solution embeddings",
    description="Embed closed issues that are missing a solution embedding; force=true re-embeds them all.",
)
def backfill_solution_embeddings(
    force: bool = Query(False, description="Re-embed closed issues even if an embedding already exists"),
    repo: TaskRepositoryInterface = Depends(get_repo),  # noqa: B008
) -> APIResponse[dict[str, Any]]:
    embedder = resolve_embedding_port()
    if embedder is None:
        return APIResponse(
            data={"embedded": 0, "skipped": 0, "failed": 0, "total_closed": 0},
            meta=Meta(request_id=None),
        )
    closed_issues = repo.list_issues(statuses=[IssueStatus.CLOSED.value])
    embedded = 0
    skipped = 0
    failed = 0
    for issue in closed_issues:
        if not force and issue.description_embedding:
            skipped += 1
            continue
        if embed_issue_solution(repo, issue, embedder):
            embedded += 1
        else:
            failed += 1
    return APIResponse(
        data={"embedded": embedded, "skipped": skipped, "failed": failed, "total_closed": len(closed_issues)},
        meta=Meta(request_id=None),
    )
