"""API router for ai_search.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# AI Search router
# ---------------------------------------------------------------------------

ai_search_router = APIRouter()


@ai_search_router.get(
    "/search-context",
    response_model=APIResponse[list],
    summary="Semantic search for context",
    description="Search issues by semantic similarity to the query text.",
)
def search_context(
    q: str = Query(..., description="Search query text"),
    threshold: float = Query(0.7, ge=0.0, le=1.0, description="Minimum similarity score"),
    limit: int = Query(10, ge=1, le=50, description="Maximum results"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list]:
    try:
        import os

        openai_api_key = os.environ.get("OPENAI_API_KEY", "")
        if not openai_api_key:
            return APIResponse(
                data=[],
                meta=Meta(request_id=None),
            )
        from openai import OpenAI

        client = OpenAI(api_key=openai_api_key)
        response = client.embeddings.create(
            model="text-embedding-ada-002",
            input=q,
        )
        embedding = response.data[0].embedding
        results = repo.search_by_embedding(embedding, threshold=threshold, limit=limit)
        return APIResponse(data=results, meta=Meta(request_id=None))
    except Exception:
        return APIResponse(data=[], meta=Meta(request_id=None))


@ai_search_router.get(
    "/similar-issues/{issue_id}",
    response_model=APIResponse[list],
    summary="Find similar issues",
    description="Find issues similar to the given issue by semantic similarity.",
)
def find_similar_issues(
    issue_id: str,
    threshold: float = Query(0.7, ge=0.0, le=1.0, description="Minimum similarity score"),
    limit: int = Query(10, ge=1, le=50, description="Maximum results"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list]:
    results = repo.find_similar_issues(issue_id, threshold=threshold, limit=limit)
    return APIResponse(data=results, meta=Meta(request_id=None))


@ai_search_router.post(
    "/issues/{issue_id}/embed",
    response_model=APIResponse[dict],
    summary="Generate embedding for issue",
    description="Generate or regenerate the embedding for an issue description.",
)
def generate_issue_embedding(
    issue_id: str,
    force: bool = Query(False, description="Force regenerate existing embedding"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    try:
        import os

        openai_api_key = os.environ.get("OPENAI_API_KEY", "")
        if not openai_api_key:
            from fastapi import HTTPException

            raise HTTPException(status_code=400, detail="OPENAI_API_KEY not configured")

        issue = repo.get_issue(issue_id)
        if issue is None:
            from fastapi import HTTPException

            raise HTTPException(status_code=404, detail="Issue not found")

        if issue.description_embedding and not force:
            return APIResponse(
                data={"issue_id": issue_id, "embedding_exists": True},
                meta=Meta(request_id=None),
            )

        text = issue.description or issue.title
        from openai import OpenAI

        client = OpenAI(api_key=openai_api_key)
        response = client.embeddings.create(
            model="text-embedding-ada-002",
            input=text,
        )
        embedding = response.data[0].embedding
        repo.update_issue_embedding(issue_id, embedding)

        return APIResponse(
            data={"issue_id": issue_id, "embedding_exists": True},
            meta=Meta(request_id=None),
        )
    except Exception as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=500, detail=str(e))
