"""API router for analysis.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Analysis router (root-cause analysis and impact assessment)
# ---------------------------------------------------------------------------

analysis_router = APIRouter()


@analysis_router.post(
    "/analyze/root-cause",
    response_model=APIResponse[list[CausalLinkResponse]],
    summary="Find root cause of test failure (DEPRECATED)",
    description=(
        "DEPRECATED: Use /analyze/link-test instead. "
        "Submit a test failure and get potential root causes ranked by "
        "confidence. Uses graph proximity analysis to link failed tests "
        "to recently closed issues."
    ),
    deprecated=True,
)
def analyze_root_cause(
    body: TestFailureRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[CausalLinkResponse]]:
    analyzer = RootCauseAnalyzer(repo)
    test_failure = TestFailure(
        test_id=body.test_id,
        test_name=body.test_name,
        error_message=body.error_message,
        stack_trace=body.stack_trace,
        component=body.component,
        labels=body.labels,
    )

    all_issues = repo.list_issues()
    closed_issues = [i for i in all_issues if i.status.value == "CLOSED"]
    causal_links = analyzer.find_root_cause(test_failure, closed_issues)

    link_data = [
        CausalLinkResponse(
            issue_id=str(link.issue.id),
            issue_title=link.issue.title,
            confidence=link.confidence,
            reasons=link.reasons,
            graph_distance=link.graph_distance,
        )
        for link in causal_links
    ]
    return APIResponse(data=link_data, meta=Meta(request_id=None))


@analysis_router.post(
    "/analyze/link-test",
    response_model=APIResponse[list[CausalLinkResponse]],
    summary="Link test failure to root cause",
    description=(
        "Submit a test failure and get potential root causes ranked by "
        "confidence. Uses graph proximity analysis to link failed tests "
        "to recently closed issues. Use this endpoint when you have a "
        "failing test and want to find which closed issue might have caused it."
    ),
)
def link_test_failure(
    body: TestFailureRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[CausalLinkResponse]]:
    analyzer = RootCauseAnalyzer(repo)
    test_failure = TestFailure(
        test_id=body.test_id,
        test_name=body.test_name,
        error_message=body.error_message,
        stack_trace=body.stack_trace,
        component=body.component,
        labels=body.labels,
    )

    all_issues = repo.list_issues()
    closed_issues = [i for i in all_issues if i.status.value == "CLOSED"]
    causal_links = analyzer.find_root_cause(test_failure, closed_issues)

    link_data = [
        CausalLinkResponse(
            issue_id=str(link.issue.id),
            issue_title=link.issue.title,
            confidence=link.confidence,
            reasons=link.reasons,
            graph_distance=link.graph_distance,
        )
        for link in causal_links
    ]
    return APIResponse(data=link_data, meta=Meta(request_id=None))


@analysis_router.get(
    "/analyze/impact/{issue_id}",
    response_model=APIResponse[ImpactAnalysisResponse],
    summary="Get impact analysis",
    description="Analyse what other issues and components would be affected.",
)
def analyze_impact(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ImpactAnalysisResponse]:
    analyzer = RootCauseAnalyzer(repo)
    impact: ImpactAnalysis = analyzer.analyze_impact(issue_id)

    impact_data = ImpactAnalysisResponse(
        issue_id=str(impact.issue_id),
        directly_affected=[
            ImpactIssueSummary(id=str(i.id), title=i.title, status=i.status.value) for i in impact.directly_affected
        ],
        transitively_affected=[
            ImpactIssueSummary(id=str(i.id), title=i.title, status=i.status.value) for i in impact.transitively_affected
        ],
        blocked_issues=[
            ImpactIssueSummary(id=str(i.id), title=i.title, status=i.status.value) for i in impact.blocked_issues
        ],
        affected_components=impact.affected_components,
        risk_level=impact.risk_level.value,
    )
    return APIResponse(data=impact_data, meta=Meta(request_id=None))


@analysis_router.get(
    "/analyze/code-impact",
    response_model=APIResponse[dict[str, Any]],
    summary="Get code-level impact analysis",
    description="Analyze code-level impact using Code-as-Graph (callers, dependencies, tests).",
)
def analyze_code_impact(
    path: str = Query(..., description="File or directory path"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict[str, Any]]:
    from socialseed_tasker.bootstrap.wiring import get_driver
    from socialseed_tasker.storage.graph_database.code_graph_repository import CodeGraphRepository

    neo4j_driver = get_driver()
    if neo4j_driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")

    cg_repo = CodeGraphRepository(neo4j_driver)

    callers = cg_repo.get_callers_by_path(path)
    dependencies = cg_repo.get_dependencies_by_path(path)
    tests = cg_repo.get_tests_for_file(path)

    caller_count = len(callers)
    if caller_count > 5:
        risk = "CRITICAL"
    elif caller_count > 2:
        risk = "HIGH"
    elif caller_count > 0:
        risk = "MEDIUM"
    else:
        risk = "LOW"

    return APIResponse(
        data={
            "path": path,
            "callers": callers,
            "dependencies": dependencies,
            "tests": tests,
            "caller_count": caller_count,
            "dependency_count": len(dependencies),
            "test_count": len(tests),
            "risk_level": risk,
        },
        meta=Meta(request_id=None),
    )


@analysis_router.get(
    "/analyze/component-impact/{component_id}",
    response_model=APIResponse[ComponentImpactAnalysisResponse],
    summary="Get component impact analysis",
    description="Analyse the impact of an entire component across the project.",
)
def analyze_component_impact(
    component_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ComponentImpactAnalysisResponse]:
    try:
        resolved_id = resolve_component_id(component_id, repo)
    except ValueError as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail=str(e))

    analyzer = RootCauseAnalyzer(repo)
    impact: ComponentImpactAnalysis = analyzer.analyze_component_impact(str(resolved_id))

    impact_data = ComponentImpactAnalysisResponse(
        component_id=str(impact.component_id),
        component_name=impact.component_name,
        total_issues=impact.total_issues,
        directly_affected_components=impact.directly_affected_components,
        transitively_affected_components=impact.transitively_affected_components,
        total_blocked_issues=impact.total_blocked_issues,
        criticality_score=impact.criticality_score,
        risk_level=impact.risk_level.value,
        affected_issues_summary=[
            ComponentImpactIssueSummary(id=i.id, title=i.title, status=i.status) for i in impact.affected_issues_summary
        ],
    )
    return APIResponse(data=impact_data, meta=Meta(request_id=None))


@analysis_router.get(
    "/graph/dependencies",
    response_model=APIResponse[DependencyGraphResponse],
    summary="Get full dependency graph",
    description="Return the complete dependency graph for visualization. Supports filtering by project.",
)
def get_full_dependency_graph(
    project: str | None = Query(None, description="Filter by project name"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[DependencyGraphResponse]:
    all_issues = repo.list_issues(project=project)
    components = {str(c.id): c.name for c in repo.list_components(project=project)}

    nodes = []
    edges = []

    for issue in all_issues:
        nodes.append(
            {
                "id": str(issue.id),
                "title": issue.title,
                "component": components.get(str(issue.component_id)),
                "status": issue.status.value,
                "priority": issue.priority.value,
            }
        )

    for issue in all_issues:
        for dep_id in issue.dependencies:
            edges.append(
                {
                    "from_node": str(issue.id),
                    "to_node": str(dep_id),
                }
            )

    return APIResponse(
        data=DependencyGraphResponse(nodes=nodes, edges=edges),
        meta=Meta(request_id=None),
    )


@analysis_router.get(
    "/graph/{issue_id}/subgraph",
    response_model=APIResponse[DependencyGraphResponse],
    summary="Get subgraph centered on issue",
    description="Return a subgraph centered on a specific issue with its dependencies and dependents.",
)
def get_subgraph(
    issue_id: str,
    depth: int = Query(2, ge=1, le=5, description="Maximum depth to traverse"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[DependencyGraphResponse]:
    from collections import deque

    center_issue = repo.get_issue(issue_id)
    if center_issue is None:
        raise IssueNotFoundError(issue_id)

    nodes: dict[str, dict] = {}
    edges: list[dict[str, str]] = []

    visited: set[str] = set()
    queue = deque([(issue_id, 0)])

    while queue:
        current_id, current_depth = queue.poplept()
        if current_id in visited or current_depth > depth:
            continue
        visited.add(current_id)

        issue = repo.get_issue(current_id)
        if issue is None:
            continue

        nodes[str(issue.id)] = {
            "id": str(issue.id),
            "title": issue.title,
            "status": issue.status.value,
            "priority": issue.priority.value,
        }

        if current_id != issue_id:
            edges.append({"from_node": current_id, "to_node": issue_id})

        if current_depth < depth:
            for dep_id in issue.dependencies:
                dep_id_str = str(dep_id)
                if dep_id_str not in visited:
                    edges.append({"from_node": str(issue.id), "to_node": dep_id_str})
                    queue.append((dep_id_str, current_depth + 1))

            for dep in repo.get_dependents(current_id):
                dep_id_str = str(dep.id)
                if dep_id_str not in visited:
                    edges.append({"from_node": dep_id_str, "to_node": str(issue.id)})
                    queue.append((dep_id_str, current_depth + 1))

    components = {str(c.id): c.name for c in repo.list_components()}
    for node_id, node_data in nodes.items():
        issue = repo.get_issue(node_id)
        if issue:
            node_data["component"] = components.get(str(issue.component_id))

    return APIResponse(
        data=DependencyGraphResponse(nodes=nodes, edges=edges),
        meta=Meta(request_id=None),
    )


@analysis_router.get(
    "/similarity/{issue_id}",
    response_model=APIResponse[list[dict[str, Any]]],
    summary="Find phantom dependencies",
    description="Find issues that are semantically similar but lack explicit dependency links. Uses RAG embeddings to detect conceptual relationships.",
)
def find_phantom_dependencies(
    issue_id: str,
    threshold: float = Query(0.7, ge=0.0, le=1.0, description="Minimum similarity score"),
    limit: int = Query(10, ge=1, le=50, description="Maximum results"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[dict[str, Any]]]:
    """Find potential phantom dependencies using semantic similarity."""
    try:
        similar = repo.find_similar_issues(issue_id, threshold=threshold, limit=limit)
        current_issue = repo.get_issue(issue_id)
        if current_issue is None:
            return APIResponse(data=[], meta=Meta(request_id=None))

        existing_deps = {str(d) for d in current_issue.dependencies}
        phantom_deps = []
        for sim_issue in similar:
            sim_id = sim_issue.get("id")
            if sim_id and sim_id not in existing_deps and sim_id != issue_id:
                phantom_deps.append({
                    "issue_id": sim_id,
                    "title": sim_issue.get("title"),
                    "similarity_score": sim_issue.get("similarity_score", 0.0),
                    "suggestion": "Consider adding explicit dependency",
                })

        return APIResponse(data=phantom_deps, meta=Meta(request_id=None))
    except Exception:
        return APIResponse(data=[], meta=Meta(request_id=None))
