"""API router for code_graph.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Code Graph Router
# ---------------------------------------------------------------------------

code_graph_router = APIRouter(tags=["code-graph"])


@code_graph_router.post("/scan")
async def code_graph_scan(
    path: str,
    incremental: bool = False,
    git_aware: bool = True,
    repo: TaskRepositoryInterface = Depends(get_repo),
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Scan a repository and extract code structure into the graph."""
    from socialseed_tasker.infrastructure.code_parser import CodeGraphParser

    parser = CodeGraphParser()

    files, symbols, imports, relationships = parser.scan_repository(
        repository_path=path,
        incremental=incremental,
        git_aware=git_aware,
    )

    saved = False
    if driver:
        try:
            from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository
            code_repo = CodeGraphRepository(driver)
            code_repo.save_scan_results(files, symbols, imports, relationships)
            saved = True
        except Exception:
            pass

    return {
        "files": len(files),
        "symbols": len(symbols),
        "imports": len(imports),
        "relationships": len(relationships),
        "saved_to_graph": saved,
    }


@code_graph_router.get("/files")
async def code_graph_files(
    limit: int = Query(50, ge=1, le=500),
    language: str | None = Query(None),
) -> dict[str, Any]:
    """List files in the code graph."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    repo = CodeGraphRepository(driver)
    files = repo.get_files(limit=limit)

    if language:
        files = [f for f in files if f.get("language") == language]

    return {"files": files, "total": len(files)}


@code_graph_router.get("/symbols")
async def code_graph_symbols(
    name: str | None = Query(None),
    symbol_type: str | None = Query(None),
    limit: int = Query(20, ge=1, le=100),
) -> dict[str, Any]:
    """Find symbols by name in the code graph."""
    from socialseed_tasker.domain.code_analysis_entities import SymbolType

    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    repo = CodeGraphRepository(driver)

    sym_type = None
    if symbol_type:
        try:
            sym_type = SymbolType(symbol_type)
        except ValueError:
            pass

    symbols = repo.find_symbols(name=name, symbol_type=sym_type, limit=limit)

    return {"symbols": symbols, "total": len(symbols)}


@code_graph_router.get("/stats")
async def code_graph_stats(driver: Any = Depends(get_code_graph_driver)) -> dict[str, Any]:
    """Get code graph statistics."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    repo = CodeGraphRepository(driver)
    stats = repo.get_stats()

    return {
        "total_files": stats.total_files,
        "total_symbols": stats.total_symbols,
        "total_relationships": stats.total_relationships,
    }


@code_graph_router.delete("")
async def code_graph_clear(driver: Any = Depends(get_code_graph_driver)) -> dict[str, str]:
    """Clear all code graph data."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected"}

    repo = CodeGraphRepository(driver)
    repo.clear()

    return {"status": "cleared"}


@code_graph_router.get("/calls/{symbol_name}")
async def code_graph_calls(
    symbol_name: str,
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get all callers of a symbol."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected"}

    repo = CodeGraphRepository(driver)
    callers = repo.get_callers(symbol_name)

    return {"symbol": symbol_name, "callers": callers, "total": len(callers)}


@code_graph_router.get("/depends/{file_path:path}")
async def code_graph_depends(
    file_path: str,
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get dependencies (imports) for a file."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected"}

    repo = CodeGraphRepository(driver)
    deps = repo.get_dependencies_by_path(file_path)

    return {"file": file_path, "dependencies": deps, "total": len(deps)}


@code_graph_router.get("/tests/{file_path:path}")
async def code_graph_tests(
    file_path: str,
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get test files for a source file."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected"}

    repo = CodeGraphRepository(driver)
    tests = repo.get_tests_for_file(file_path)

    return {"file": file_path, "tests": tests, "total": len(tests)}


@code_graph_router.get("/issues/{file_path:path}")
async def get_issues_for_file(
    file_path: str,
    limit: int = Query(20, ge=1, le=100),
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get all issues that affected a file."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected", "issues": []}

    repo = CodeGraphRepository(driver)
    issues = repo.get_issues_affecting_file(file_path, limit)

    return {"file_path": file_path, "issues": issues, "total": len(issues)}


# ---------------------------------------------------------------------------
# Impact Analysis endpoints
# ---------------------------------------------------------------------------


@code_graph_router.get("/symbols/{symbol_id}/callers")
async def get_symbol_callers(
    symbol_id: str,
    transitive: bool = Query(False, description="Include transitive callers"),
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get all symbols that call this symbol (dependents)."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected", "callers": []}

    repo = CodeGraphRepository(driver)
    if transitive:
        callers = repo.get_transitive_callers(symbol_id)
    else:
        callers = repo.get_direct_callers(symbol_id)
    
    return {"symbol_id": symbol_id, "transitive": transitive, "callers": callers, "total": len(callers)}


@code_graph_router.get("/symbols/{symbol_id}/callees")
async def get_symbol_callees(
    symbol_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get all symbols that this symbol calls (dependencies)."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected", "callees": []}

    repo = CodeGraphRepository(driver)
    callees = repo.get_direct_callees(symbol_id)
    
    return {"symbol_id": symbol_id, "callees": callees, "total": len(callees)}


@code_graph_router.get("/symbols/{symbol_id}")
async def get_symbol_by_id(
    symbol_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Get a CodeSymbol by its ID."""
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected"}

    repo = CodeGraphRepository(driver)
    symbol = repo.get_symbol_by_id(symbol_id)
    
    if not symbol:
        return {"error": "Symbol not found", "symbol_id": symbol_id}
    
    return {"symbol": symbol}


@code_graph_router.post("/analyze/impact")
async def analyze_impact(
    symbol_id: str = Body(..., description="The CodeSymbol ID to analyze"),
    include_transitive: bool = Body(True, description="Include transitive callers"),
    driver: Any = Depends(get_code_graph_driver),
) -> dict[str, Any]:
    """Perform impact analysis for a CodeSymbol.
    
    Returns:
    - direct callers (what depends on this)
    - direct callees (what this depends on)
    - transitive callers (full dependency tree)
    - risk level based on impact scope
    """
    from socialseed_tasker.infrastructure.neo4j_code_graph_repository import CodeGraphRepository

    if not driver:
        return {"error": "Neo4j not connected"}

    repo = CodeGraphRepository(driver)
    result = repo.analyze_impact(symbol_id, include_transitive)
    
    return result
