"""API router for commit.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Commit router
# ---------------------------------------------------------------------------

commit_router = APIRouter()


def _commit_to_response(commit: "Commit") -> "CommitResponse":  # type: ignore[valid-type]
    """Convert domain Commit to API response."""
    return CommitResponse(
        sha=commit.sha,
        message=commit.message,
        author_name=commit.authorName,
        author_email=commit.authorEmail,
        timestamp=commit.timestamp,
        is_ai_generated=commit.isAiGenerated,
        branch=commit.branch,
        additions=commit.additions,
        deletions=commit.deletions,
        files_changed=commit.filesChanged,
    )


@commit_router.post(
    "/commits",
    response_model=APIResponse[CommitResponse],
    summary="Create a new commit",
    description="Record a new commit in the system.",
)
def create_commit(
    body: CommitCreateRequest,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[CommitResponse]:
    """Create a new commit."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.domain.entities import Commit

    commit = Commit(
        sha=body.sha,
        message=body.message,
        authorName=body.author_name,
        authorEmail=body.author_email,
        isAiGenerated=body.is_ai_generated,
        branch=body.branch,
        additions=body.additions,
        deletions=body.deletions,
        filesChanged=body.files_changed,
    )

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    repo.create_commit(commit)

    return APIResponse(data=_commit_to_response(commit), meta=Meta(request_id=None))


@commit_router.get(
    "/commits/stats",
    response_model=APIResponse[CommitStatsResponse],
    summary="Get commit statistics",
    description="Get commit statistics by author (human vs AI).",
)
def get_commit_stats(
    since: datetime | None = Query(None, description="Filter by start date"),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[CommitStatsResponse]:
    """Get commit statistics."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    stats = repo.get_author_stats(since=since)

    return APIResponse(data=CommitStatsResponse(**stats), meta=Meta(request_id=None))


@commit_router.get(
    "/commits/{sha}",
    response_model=APIResponse[CommitResponse],
    summary="Get commit by SHA",
    description="Get a commit by its SHA hash.",
)
def get_commit(
    sha: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[CommitResponse]:
    """Get a commit by SHA."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    commit = repo.get_commit(sha)

    if not commit:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="Commit not found")

    return APIResponse(data=_commit_to_response(commit), meta=Meta(request_id=None))


@commit_router.get(
    "/commits",
    response_model=APIResponse[list[CommitResponse]],
    summary="List commits",
    description="List commits with optional filters.",
)
def list_commits(
    branch: str | None = Query(None, description="Filter by branch"),
    author: str | None = Query(None, description="Filter by author name"),
    is_ai_generated: bool | None = Query(None, description="Filter by AI generated"),
    since: datetime | None = Query(None, description="Filter by start date"),
    until: datetime | None = Query(None, description="Filter by end date"),
    limit: int = Query(50, ge=1, le=100),
    skip: int = Query(0, ge=0),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[list[CommitResponse]]:
    """List commits."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    commits = repo.list_commits(
        branch=branch,
        author=author,
        is_ai_generated=is_ai_generated,
        since=since,
        until=until,
        limit=limit,
        skip=skip,
    )

    return APIResponse(
        data=[_commit_to_response(c) for c in commits],
        meta=Meta(request_id=None),
    )


@commit_router.post(
    "/commits/{sha}/link/agent/{agent_id}",
    response_model=APIResponse[dict],
    summary="Link commit to agent",
    description="Create (Agent)-[:AUTHORED]->(Commit) relationship.",
)
def link_commit_to_agent(
    sha: str,
    agent_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Link commit to an agent."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    repo.link_commit_to_agent(sha, agent_id)

    return APIResponse(data={"status": "linked"}, meta=Meta(request_id=None))


@commit_router.post(
    "/commits/{sha}/link/user/{user_id}",
    response_model=APIResponse[dict],
    summary="Link commit to user",
    description="Create (User)-[:AUTHORED]->(Commit) relationship.",
)
def link_commit_to_user(
    sha: str,
    user_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Link commit to a user."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    repo.link_commit_to_user(sha, user_id)

    return APIResponse(data={"status": "linked"}, meta=Meta(request_id=None))


@commit_router.post(
    "/commits/{sha}/link/issue/{issue_id}",
    response_model=APIResponse[dict],
    summary="Link commit to issue",
    description="Create (Issue)-[:RESOLVED_BY]->(Commit) relationship.",
)
def link_commit_to_issue(
    sha: str,
    issue_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Link commit to an issue (mark as resolved)."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    repo.link_commit_to_issue(sha, issue_id)

    return APIResponse(data={"status": "linked"}, meta=Meta(request_id=None))


@commit_router.get(
    "/commits/issue/{issue_id}",
    response_model=APIResponse[list[CommitResponse]],
    summary="Get commits for issue",
    description="Get all commits that resolved an issue.",
)
def get_commits_for_issue(
    issue_id: str,
    limit: int = Query(50, ge=1, le=100),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[list[CommitResponse]]:
    """Get commits for an issue."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    commits = repo.get_commits_for_issue(issue_id, limit=limit)

    return APIResponse(
        data=[_commit_to_response(c) for c in commits],
        meta=Meta(request_id=None),
    )


@commit_router.get(
    "/commits/file/{file_path:path}",
    response_model=APIResponse[list[dict]],
    summary="Get commits for file",
    description="Get commit history for a file.",
)
def get_commits_for_file(
    file_path: str,
    limit: int = Query(20, ge=1, le=100),
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[list[dict]]:
    """Get commits for a file."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    results = repo.get_commits_for_file(file_path, limit=limit)

    return APIResponse(
        data=[
            {
                "commit": _commit_to_response(r["commit"]),
                "change_type": r["change_type"],
            }
            for r in results
        ],
        meta=Meta(request_id=None),
    )


@commit_router.delete(
    "/commits/{sha}",
    response_model=APIResponse[dict],
    summary="Delete commit",
    description="Delete a commit from the system.",
)
def delete_commit(
    sha: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Delete a commit."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_commit_repository import CommitRepository

    repo = CommitRepository(driver)
    repo.delete_commit(sha)

    return APIResponse(data={"status": "deleted"}, meta=Meta(request_id=None))
