"""API router for components.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Components router
# ---------------------------------------------------------------------------

components_router = APIRouter()


@components_router.get(
    "/projects",
    response_model=APIResponse[list[str]],
    summary="List projects",
    description="List all unique project names in the system.",
)
def list_projects(
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[str]]:
    projects = repo.list_projects()
    return APIResponse(data=projects, meta=Meta(request_id=None))


@components_router.post(
    "/components",
    response_model=APIResponse[ComponentResponse],
    status_code=201,
    summary="Create a component",
    description="Create a new component to group issues.",
)
def create_component(
    body: ComponentCreateRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    from fastapi import HTTPException

    from socialseed_tasker.domain.entities import Component
    from socialseed_tasker.domain import (
        ComponentNameValidationError,
        sanitize_component_name,
        validate_component_name,
    )

    try:
        validated_name = validate_component_name(body.name)
    except ComponentNameValidationError as e:
        raise HTTPException(status_code=400, detail=str(e))

    sanitized_name = sanitize_component_name(validated_name)
    sanitized_description = sanitize_component_name(body.description or "")

    comp = Component(name=sanitized_name, description=sanitized_description, project=body.project, labels=body.labels)
    repo.create_component(comp)
    return APIResponse(data=_component_to_response(comp), meta=Meta(request_id=None))


@components_router.get(
    "/components",
    response_model=APIResponse[PaginatedResponse[ComponentResponse]],
    summary="List components",
    description="List all components, optionally filtered by project or name. Supports pagination.",
)
def list_components(
    project: str | None = Query(None, description="Filter by project"),
    name: str | None = Query(None, description="Filter by exact name"),
    page: int = Query(1, ge=1, description="Page number (starts at 1, default: 1)"),
    limit: int = Query(20, ge=1, le=100, description="Items per page (default: 20, max: 100)"),
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    if name:
        comp = repo.get_component_by_name(name, project)
        components = [comp] if comp else []
    else:
        components = repo.list_components(project=project)

    total = len(components)
    start = (page - 1) * limit
    end = start + limit
    page_items = components[start:end]

    return APIResponse(
        data=_paginated([_component_to_response(c) for c in page_items], page, limit, total),
        meta=Meta(request_id=None),
    )


@components_router.get(
    "/components/{component_id}",
    response_model=APIResponse[ComponentResponse],
    summary="Get component details",
    description="Retrieve full details of a single component.",
    responses={404: {"description": "Component not found"}},
)
def get_component(
    component_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    comp = repo.get_component(component_id)
    if comp is None:
        raise ComponentNotFoundError(component_id)
    return APIResponse(data=_component_to_response(comp), meta=Meta(request_id=None))


@components_router.patch(
    "/components/{component_id}",
    response_model=APIResponse[ComponentResponse],
    summary="Update a component",
    description="Update one or more fields of a component.",
)
def update_component(
    component_id: str,
    body: dict[str, Any],
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ComponentResponse]:

    try:
        updates = {}
        if "name" in body:
            updates["name"] = body["name"]
        if "description" in body:
            updates["description"] = body["description"]
        if "project" in body:
            updates["project"] = body["project"]

        if not updates:
            raise ValueError("At least one field to update must be provided")

        updated = repo.update_component(component_id, updates)
        return APIResponse(data=_component_to_response(updated), meta=Meta(request_id=None))
    except FileNotFoundError:
        raise ComponentNotFoundError(component_id)
    except ValueError as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail=str(e))


@components_router.delete(
    "/components/{component_id}",
    response_model=APIResponse[dict[str, Any]],
    summary="Delete a component",
    description="Delete a component. Fails if component has issues unless force=true.",
)
def delete_component(
    component_id: str,
    force: bool = Query(False, description="Force deletion even if component has issues"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict[str, str]]:
    from socialseed_tasker.application.actions import ComponentHasIssuesError, delete_component_action

    try:
        delete_component_action(repo, component_id, force=force)
        return APIResponse(data={"deleted": component_id}, meta=Meta(request_id=None))
    except FileNotFoundError:
        raise ComponentNotFoundError(component_id)
    except ComponentHasIssuesError as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=409, detail=str(e))
