"""API router for Component Dependency.

Generated by refactoring for SOLID compliance.
"""

from __future__ import annotations

import logging
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)



components_dep_router = APIRouter()


@components_dep_router.post(
    "/components/{component_id}/dependencies",
    response_model=APIResponse[dict[str, str]],
    summary="Add component dependency",
    description="Create a [:DEPENDS_ON] relationship between two components.",
    responses={
        404: {"description": "Component not found"},
        400: {"description": "Cannot depend on self"},
    },
)
def add_component_dependency(
    component_id: str,
    body: dict[str, str],
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    from fastapi import HTTPException

    depends_on_id = body.get("depends_on_id")
    if not depends_on_id:
        raise HTTPException(status_code=400, detail="depends_on_id is required")

    if component_id == depends_on_id:
        raise HTTPException(status_code=400, detail="A component cannot depend on itself")

    existing = repo.get_component(component_id)
    if existing is None:
        raise ComponentNotFoundError(component_id)

    existing_target = repo.get_component(depends_on_id)
    if existing_target is None:
        raise ComponentNotFoundError(depends_on_id)

    repo.add_component_dependency(component_id, depends_on_id)
    return APIResponse(
        data={"component_id": component_id, "depends_on_id": depends_on_id},
        meta=Meta(request_id=None),
    )


@components_dep_router.get(
    "/components/{component_id}/dependencies",
    response_model=APIResponse[list[ComponentResponse]],
    summary="Get component dependencies",
    description="List components that this component depends on.",
    responses={404: {"description": "Component not found"}},
)
def get_component_dependencies(
    component_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    existing = repo.get_component(component_id)
    if existing is None:
        raise ComponentNotFoundError(component_id)

    deps = repo.get_component_dependencies(component_id)
    return APIResponse(
        data=[_component_to_response(c) for c in deps],
        meta=Meta(request_id=None),
    )


@components_dep_router.get(
    "/components/{component_id}/dependents",
    response_model=APIResponse[list[ComponentResponse]],
    summary="Get component dependents",
    description="List components that depend on this component.",
    responses={404: {"description": "Component not found"}},
)
def get_component_dependents(
    component_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    existing = repo.get_component(component_id)
    if existing is None:
        raise ComponentNotFoundError(component_id)

    dependents = repo.get_component_dependents(component_id)
    return APIResponse(
        data=[_component_to_response(c) for c in dependents],
        meta=Meta(request_id=None),
    )
