"""API router for constraints.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constraints router
# ---------------------------------------------------------------------------

constraints_router = APIRouter()


@constraints_router.post(
    "",
    response_model=APIResponse[ConstraintLoadResponse],
    summary="Load constraints from config",
    description="Load constraints from a YAML config file and store in Neo4j.",
)
def load_constraints(
    config: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ConstraintLoadResponse]:
    from socialseed_tasker.application.actions import load_constraints_from_config_action
    from socialseed_tasker.application.constraints import ConstraintConfig

    constraint_config = ConstraintConfig(**config)
    result = load_constraints_from_config_action(repo, constraint_config)

    return APIResponse(
        data=ConstraintLoadResponse(**result),
        meta=Meta(request_id=None),
    )


@constraints_router.get(
    "",
    response_model=APIResponse[list[ConstraintResponse]],
    summary="List constraints",
    description="List all constraints, optionally filtered by category.",
)
def list_constraints(
    category: str | None = Query(None, description="Filter by category"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[ConstraintResponse]]:
    from socialseed_tasker.application.actions import list_constraints_action

    constraints = list_constraints_action(repo, category=category)

    return APIResponse(
        data=[
            ConstraintResponse(
                id=str(c.id),
                category=c.category.value,
                level=c.level.value,
                pattern=c.pattern,
                service=c.service,
                target=c.target,
                from_layer=c.from_layer,
                to_layer=c.to_layer,
                rule_type=c.rule_type,
                max_depth=c.max_depth,
                required=c.required,
                description=c.description,
                status=c.status.value,
            )
            for c in constraints
        ],
        meta=Meta(request_id=None),
    )


@constraints_router.get(
    "/constraints/validate",
    response_model=APIResponse[ConstraintValidationResponse],
    summary="Validate constraints",
    description="Validate all active constraints against current project state.",
)
def validate_constraints(
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ConstraintValidationResponse]:
    from socialseed_tasker.application.actions import validate_constraints_action

    result = validate_constraints_action(repo)

    return APIResponse(
        data=ConstraintValidationResponse(
            is_valid=result.is_valid,
            violations=[
                ConstraintViolationResponse(
                    constraint_id=str(v.constraint_id),
                    constraint_description=v.constraint_description,
                    level=v.level.value,
                    category=v.category.value,
                    affected_resource=v.affected_resource,
                    message=v.message,
                    suggestion=v.suggestion,
                )
                for v in result.violations
            ],
            hard_violations_count=len(result.hard_violations),
            soft_violations_count=len(result.soft_violations),
        ),
        meta=Meta(request_id=None),
    )
