"""API router for cost_analytics.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Cost Analytics router
# ---------------------------------------------------------------------------

cost_analytics_router = APIRouter()


@cost_analytics_router.get(
    "/cost-per-component",
    response_model=APIResponse[list],
    summary="Get cost per component",
    description="Get cost breakdown by component for closed issues with time tracking.",
)
def get_cost_per_component(repo: TaskRepositoryInterface = Depends(get_repo)):
    costs = repo.get_cost_per_component()
    return APIResponse(data=costs, meta=Meta(request_id=None))


@cost_analytics_router.get(
    "/cost-per-epic",
    response_model=APIResponse[list],
    summary="Get cost per epic",
    description="Get cost breakdown by epic for closed issues with time tracking.",
)
def get_cost_per_epic(repo: TaskRepositoryInterface = Depends(get_repo)):
    costs = repo.get_cost_per_epic()
    return APIResponse(data=costs, meta=Meta(request_id=None))


@cost_analytics_router.get(
    "/cost-per-project",
    response_model=APIResponse[list],
    summary="Get cost per project",
    description="Get cost breakdown by project for closed issues with time tracking.",
)
def get_cost_per_project(repo: TaskRepositoryInterface = Depends(get_repo)):
    costs = repo.get_cost_per_project()
    return APIResponse(data=costs, meta=Meta(request_id=None))


@cost_analytics_router.get(
    "/cost-summary",
    response_model=APIResponse[dict],
    summary="Get cost summary",
    description="Get overall cost summary for all closed issues with time tracking.",
)
def get_cost_summary(repo: TaskRepositoryInterface = Depends(get_repo)):
    summary = repo.get_cost_summary()
    return APIResponse(data=summary, meta=Meta(request_id=None))
