"""API router for epic.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Epic router
# ---------------------------------------------------------------------------

epic_router = APIRouter()


@epic_router.post(
    "/epics",
    response_model=APIResponse[dict],
    status_code=201,
    summary="Create an epic",
    description="Create a new epic to group related issues.",
)
def create_epic(
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    from uuid import uuid4

    epic = Epic(
        id=uuid4(),
        name=body.get("name", ""),
        description=body.get("description", ""),
        objective_id=body.get("objective_id"),
        status=EpicStatus(body.get("status", "OPEN")),
    )
    repo.create_epic(epic)
    return APIResponse(
        data={"id": str(epic.id), "name": epic.name},
        meta=Meta(request_id=None),
    )


@epic_router.get(
    "/epics",
    response_model=APIResponse[list],
    summary="List epics",
    description="List all epics in the system.",
)
def list_epics(repo: TaskRepositoryInterface = Depends(get_repo)):
    epics = repo.list_epics()
    return APIResponse(
        data=[{"id": str(e.id), "name": e.name, "status": e.status.value} for e in epics],
        meta=Meta(request_id=None),
    )


@epic_router.get(
    "/epics/{epic_id}",
    response_model=APIResponse[dict],
    summary="Get an epic",
    description="Get details of a specific epic.",
)
def get_epic(epic_id: str, repo: TaskRepositoryInterface = Depends(get_repo)):
    epic = repo.get_epic(epic_id)
    if epic is None:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="Epic not found")
    return APIResponse(
        data={
            "id": str(epic.id),
            "name": epic.name,
            "description": epic.description,
            "status": epic.status.value,
            "objective_id": str(epic.objective_id) if epic.objective_id else None,
        },
        meta=Meta(request_id=None),
    )


@epic_router.delete(
    "/epics/{epic_id}",
    response_model=APIResponse[dict],
    summary="Delete an epic",
    description="Delete an epic.",
)
def delete_epic(epic_id: str, repo: TaskRepositoryInterface = Depends(get_repo)):
    repo.delete_epic(epic_id)
    return APIResponse(data={"deleted": epic_id}, meta=Meta(request_id=None))


@epic_router.patch(
    "/epics/{epic_id}",
    response_model=APIResponse[dict],
    summary="Update an epic",
    description="Update an epic.",
)
def update_epic(
    epic_id: str,
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    repo.update_epic(epic_id, body)
    return APIResponse(data={"updated": epic_id}, meta=Meta(request_id=None))


@epic_router.post(
    "/epics/{epic_id}/issues",
    response_model=APIResponse[dict],
    summary="Link issues to epic",
    description="Link multiple issues to an epic.",
)
def link_issues_to_epic(
    epic_id: str,
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
):

    issue_ids = body.get("issue_ids", [])
    for issue_id in issue_ids:
        repo.link_issue_to_epic(issue_id, epic_id)
    return APIResponse(
        data={"epic_id": epic_id, "linked_issues": len(issue_ids)},
        meta=Meta(request_id=None),
    )
