"""API router for issues.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Issues router
# ---------------------------------------------------------------------------

issues_router = APIRouter()


@issues_router.post(
    "/issues",
    response_model=APIResponse[IssueResponse],
    status_code=201,
    summary="Create a new issue",
    description=(
        "Create a new issue in the task management system. "
        "The issue will be linked to an existing component and can have "
        "labels and architectural constraints assigned."
    ),
    responses={
        201: {"description": "Issue created successfully"},
        404: {"description": "Component not found"},
        400: {"description": "Validation error"},
    },
)
def create_issue(
    body: IssueCreateRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    """Create a new issue.

    Creates a new issue linked to a component. The issue title is validated
    and sanitized to prevent XSS attacks. Descriptions are also sanitized.

    Args:
        body: Issue creation request with title, description, priority, etc.
        repo: Repository dependency for data access.

    Returns:
        APIResponse with the created IssueResponse.

    Raises:
        HTTPException 400: If title validation fails.
        HTTPException 404: If the specified component doesn't exist.

    Example:
        ```bash
        curl -X POST /api/v1/issues \\
          -H "Content-Type: application/json" \\
          -d '{"title": "Fix auth bug", "priority": "HIGH", "component_id": "uuid-here"}'
        ```

        Response:
        ```json
        {
          "data": {
            "id": "uuid-here",
            "title": "Fix auth bug",
            "status": "todo",
            "priority": "HIGH",
            ...
          },
          "meta": {"timestamp": "...", "warnings": null}
        }
        ```
    """
    from fastapi import HTTPException

    from socialseed_tasker.core.validation import (
        IssueDescriptionValidationError,
        IssueTitleValidationError,
        sanitize_issue_description,
        sanitize_issue_title,
        validate_issue_title,
    )

    try:
        validated_title = validate_issue_title(body.title)
    except IssueTitleValidationError as e:
        raise HTTPException(status_code=400, detail=str(e))

    try:
        sanitized_description = sanitize_issue_description(body.description or "")
    except IssueDescriptionValidationError as e:
        raise HTTPException(status_code=400, detail=str(e))

    sanitized_title = sanitize_issue_title(validated_title)

    issue, warnings = create_issue_action(
        repo,
        title=sanitized_title,
        component_id=body.component_id,
        description=sanitized_description,
        priority=body.priority,
        labels=body.labels,
        architectural_constraints=body.architectural_constraints,
    )
    return APIResponse(
        data=_issue_to_response(issue), meta=Meta(request_id=None, warnings=warnings if warnings else None)
    )


@issues_router.get(
    "/issues",
    response_model=APIResponse[PaginatedResponse[IssueResponse]],
    summary="List issues",
    description=(
        "List issues with optional filters for status, component, and labels. "
        "Supports pagination via page and limit query parameters."
    ),
    operation_id="list_all_issues",
)
def list_issues(
    status: str | None = Query(None, description="Filter by status"),
    component: str | None = Query(None, description="Filter by component ID"),
    project: str | None = Query(None, description="Filter by project name"),
    page: int = Query(1, ge=1, description="Page number (starts at 1, default: 1)"),
    limit: int = Query(20, ge=1, le=100, description="Items per page (default: 20, max: 100)"),
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    """List issues with optional filters and pagination.

    Retrieves a paginated list of issues. Supports filtering by status,
    component, and project. Results are sorted by creation date (newest first).

    Args:
        status: Comma-separated list of statuses to filter (e.g., "todo,in_progress")
        component: UUID of the component to filter by
        project: Project name to filter by
        page: Page number starting at 1
        limit: Number of items per page (max 100)
        repo: Repository dependency for data access.

    Returns:
        APIResponse with PaginatedResponse containing IssueResponse items.

    Example:
        ```bash
        # Get first page of open issues
        curl "/api/v1/issues?status=todo,in_progress&page=1&limit=20"

        # Filter by project
        curl "/api/v1/issues?project=socialseed-tasker"
        ```

        Response:
        ```json
        {
          "data": {
            "items": [...],
            "pagination": {
              "page": 1,
              "limit": 20,
              "total": 150,
              "has_next": true,
              "has_prev": false
            }
          }
        }
        ```
    """
    status_list = [s.strip() for s in status.split(",") if s.strip()] if status else []
    all_issues = repo.list_issues(component_id=component, statuses=status_list, project=project)
    total = len(all_issues)
    start = (page - 1) * limit
    end = start + limit
    page_items = all_issues[start:end]

    return APIResponse(
        data=_paginated([_issue_to_response(i) for i in page_items], page, limit, total),
        meta=Meta(request_id=None),
    )


@issues_router.get(
    "/issues/{issue_id}",
    response_model=APIResponse[IssueResponse],
    summary="Get issue details",
    description="Retrieve full details of a single issue by its ID.",
    responses={404: {"description": "Issue not found"}},
)
def get_issue(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    """Get a single issue by ID.

    Retrieves full details of an issue including dependencies, blocks,
    reasoning logs, and agent progress manifest.

    Args:
        issue_id: UUID or short ID (8+ chars) of the issue.
        repo: Repository dependency for data access.

    Returns:
        APIResponse with the IssueResponse containing all issue details.

    Raises:
        IssueNotFoundError: If the issue doesn't exist.

    Example:
        ```bash
        curl /api/v1/issues/550e8400-e29b-41d4-a716-446655440000
        ```

        Response:
        ```json
        {
          "data": {
            "id": "550e8400-e29b-41d4-a716-446655440000",
            "title": "Fix login bug",
            "status": "in_progress",
            "priority": "HIGH",
            "dependencies": ["uuid-1", "uuid-2"],
            "reasoning_logs": [...],
            "manifest_todo": [...],
            ...
          }
        }
        ```
    """
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    return APIResponse(data=_issue_to_response(issue), meta=Meta(request_id=None))


@issues_router.get(
    "/issues/{issue_id}/component",
    response_model=APIResponse[dict],
    summary="Get issue's component via relationship",
    description="Get the Component that this Issue belongs to, following the BELONGS_TO relationship.",
    responses={404: {"description": "Issue or Component not found"}},
)
def get_issue_component(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    issue = repo.get_issue(str(issue_id))
    if issue is None:
        raise IssueNotFoundError(issue_id)

    component = repo.get_component(str(issue.component_id)) if issue.component_id else None

    return APIResponse(
        data={"issue_id": issue_id, "component": component.name if component else None},
        meta=Meta(request_id=None),
    )


@issues_router.get(
    "/issues/{issue_id}/deployments",
    response_model=APIResponse[list],
    summary="Get deployments for an issue",
    description="Get all deployments where this issue was released.",
)
def get_issue_deployments(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list]:
    deployments = repo.get_issue_deployments(issue_id)
    return APIResponse(data=deployments, meta=Meta(request_id=None))


@issues_router.patch(
    "/issues/{issue_id}",
    response_model=APIResponse[IssueResponse],
    summary="Update an issue",
    description="Apply partial updates to an issue. Supports status transitions and field updates.",
    responses={
        404: {"description": "Issue not found"},
        409: {"description": "Conflict - invalid status transition"},
    },
)
def update_issue(
    issue_id: str,
    body: IssueUpdateRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    """Update an issue with partial field updates.

    Applies partial updates to an existing issue. Only fields included in the
    request body will be updated. Supports status transitions, priority changes,
    and agent work status updates.

    Args:
        issue_id: UUID or short ID (8+ chars) of the issue.
        body: IssueUpdateRequest with fields to update.
        repo: Repository dependency for data access.

    Returns:
        APIResponse with the updated IssueResponse.

    Raises:
        IssueNotFoundError: If the issue doesn't exist.
        HTTPException 400: If attempting invalid status transitions.
        HTTPException 409: If closing an issue with open dependencies.

    Example:
        ```bash
        # Update status and priority
        curl -X PATCH /api/v1/issues/uuid-here \\
          -H "Content-Type: application/json" \\
          -d '{"status": "in_progress", "priority": "HIGH"}'

        # Mark as agent working
        curl -X PATCH /api/v1/issues/uuid-here \\
          -d '{"agent_working": true}'
        ```
    """
    from fastapi import HTTPException

    existing = repo.get_issue(issue_id)
    if existing is None:
        raise IssueNotFoundError(issue_id)

    updates = body.model_dump(exclude_unset=True)
    if not updates:
        return APIResponse(data=_issue_to_response(existing), meta=Meta(request_id=None))

    if "status" in updates:
        new_status = IssueStatus(updates["status"])
        if existing.status == IssueStatus.CLOSED and new_status != IssueStatus.CLOSED:
            raise HTTPException(
                status_code=400,
                detail="Cannot reopen a closed issue. Use a separate reopen endpoint or create a new issue.",
            )
        if "agent_working" in updates and new_status not in (
            IssueStatus.OPEN,
            IssueStatus.IN_PROGRESS,
            IssueStatus.BLOCKED,
        ):
            raise HTTPException(
                status_code=400,
                detail="agent_working can only be set on OPEN, IN_PROGRESS, or BLOCKED issues.",
            )

    if (
        "agent_working" in updates
        and "status" not in updates
        and existing.status
        not in (
            IssueStatus.OPEN,
            IssueStatus.IN_PROGRESS,
            IssueStatus.BLOCKED,
        )
    ):
        raise HTTPException(
            status_code=400,
            detail="agent_working can only be set on OPEN, IN_PROGRESS, or BLOCKED issues.",
        )

    updated = repo.update_issue(issue_id, updates)
    return APIResponse(data=_issue_to_response(updated), meta=Meta(request_id=None))


@issues_router.delete(
    "/issues/{issue_id}",
    status_code=204,
    summary="Delete an issue",
    description="Permanently delete an issue and all its relationships.",
    responses={404: {"description": "Issue not found"}},
)
def delete_issue(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    repo.delete_issue(issue_id)


@issues_router.post(
    "/issues/{issue_id}/close",
    response_model=APIResponse[IssueResponse],
    summary="Close an issue",
    description=("Close an issue. Fails if the issue has open dependencies or is already closed."),
    responses={
        404: {"description": "Issue not found"},
        409: {"description": "Already closed or has open dependencies"},
    },
)
def close_issue(
    issue_id: str,
    commit_sha: str | None = Body(None, description="Git commit SHA that resolved this issue"),
    resolution: str = Body("implemented", description="Resolution type: implemented, duplicate, wontfix, etc."),
    affected_files: list[str] = Body([], description="Files affected by this issue"),
    force: bool = Query(False, description="Force close even with policy violations"),
    repo: TaskRepositoryInterface = Depends(get_repo),
    request: Request = Depends(get_code_graph_driver),
):
    from socialseed_tasker.core.project_analysis.analyzer import ArchitecturalAnalyzer
    
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    
    if not force and issue.component_id:
        analyzer = ArchitecturalAnalyzer(repo)
        validation = analyzer.validate_issue_creation(issue)
        has_blocker = any(v.severity.value == "ERROR" for v in validation.violations)
        if has_blocker:
            from fastapi import HTTPException
            raise HTTPException(
                status_code=409,
                detail={
                    "error": "Policy violation - BLOCKER severity",
                    "violations": [
                        {"rule": v.rule_name, "message": v.message}
                        for v in validation.violations
                    ],
                    "hint": "Use ?force=true to override (not recommended)"
                }
            )
    
    issue = close_issue_action(repo, issue_id, commit_sha, resolution)

    if affected_files and request:
        try:
            if hasattr(request, 'driver'):
                driver = request.driver
            elif hasattr(request.app.state, 'driver'):
                driver = request.app.state.driver
                if hasattr(driver, 'driver'):
                    driver = driver.driver
            else:
                driver = None

            if driver:
                from socialseed_tasker.storage.graph_database.code_graph_repository import CodeGraphRepository
                code_repo = CodeGraphRepository(driver)
                for file_path in affected_files:
                    code_repo.link_issue_to_file(issue_id, file_path)
        except Exception:
            pass

    return APIResponse(data=_issue_to_response(issue), meta=Meta(request_id=None))


@issues_router.get(
    "/issues/{issue_id}/resolution",
    response_model=APIResponse[dict],
    summary="Get issue resolution",
    description="Get the commit SHA and resolution details that closed this issue.",
)
def get_issue_resolution(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)
    
    resolution_data = {
        "issue_id": issue_id,
        "title": issue.title,
        "status": issue.status.value if hasattr(issue.status, 'value') else str(issue.status),
        "resolved_by_commit_sha": issue.resolved_by_commit_sha,
        "resolution": issue.resolution,
        "closed_at": issue.closed_at.isoformat() if issue.closed_at else None,
    }
    
    return APIResponse(data=resolution_data, meta=Meta(request_id=None))


@issues_router.post(
    "/issues/{issue_id}/link-github",
    response_model=APIResponse[IssueResponse],
    summary="Link GitHub issue",
    description="Link a Tasker issue to a GitHub issue for causal mirroring.",
)
def link_github_issue(
    issue_id: str,
    github_issue_url: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    import re

    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    match = re.search(r"github\.com/([^/]+)/([^/]+)/issues/(\d+)", github_issue_url)
    if not match:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail="Invalid GitHub issue URL")

    github_issue_number = int(match.group(3))

    updates = {
        "github_issue_url": github_issue_url,
        "github_issue_number": github_issue_number,
    }
    updated_issue = repo.update_issue(issue_id, updates)
    return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))


@issues_router.post(
    "/issues/{issue_id}/unlink-github",
    response_model=APIResponse[IssueResponse],
    summary="Unlink GitHub issue",
    description="Unlink a Tasker issue from its GitHub issue.",
)
def unlink_github_issue(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    updates = {
        "github_issue_url": None,
        "github_issue_number": None,
    }
    updated_issue = repo.update_issue(issue_id, updates)
    return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))


@issues_router.post(
    "/issues/{issue_id}/mirror-root-cause",
    response_model=APIResponse[dict],
    summary="Mirror root cause analysis to GitHub",
    description="Post root cause analysis as a comment on the linked GitHub issue.",
)
def mirror_root_cause(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    from socialseed_tasker.core.services.github_mirror import GitHubMirroringService

    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    if not hasattr(issue, "github_issue_number") or not issue.github_issue_number:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail="Issue not linked to GitHub")

    from socialseed_tasker.core.project_analysis.analyzer import ArchitecturalAnalyzer

    analyzer = ArchitecturalAnalyzer(repo)

    causal_links = analyzer.analyze_root_cause_issues([issue])

    if not causal_links:
        return APIResponse(
            data={"mirrored": False, "message": "No causal links found"},
            meta=Meta(request_id=None),
        )

    analysis_data = {
        "confidence": max([c.confidence for c in causal_links]) if causal_links else 0.0,
        "primary_factor": "Multiple causal factors identified",
        "causal_links": [{"issue_id": str(c.issue.id), "issue_title": c.issue.title} for c in causal_links[:5]],
    }

    mirror = GitHubMirroringService()
    result = mirror.mirror_root_cause(issue.github_issue_number, analysis_data)
    mirror.close()

    return APIResponse(
        data={"mirrored": True, "comment_url": result.get("html_url")},
        meta=Meta(request_id=None),
    )


@issues_router.post(
    "/issues/{issue_id}/mirror-impact",
    response_model=APIResponse[dict],
    summary="Mirror impact analysis to GitHub",
    description="Post impact analysis as a comment on the linked GitHub issue.",
)
def mirror_impact(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    from socialseed_tasker.core.services.github_mirror import GitHubMirroringService

    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    if not hasattr(issue, "github_issue_number") or not issue.github_issue_number:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail="Issue not linked to GitHub")

    from socialseed_tasker.core.project_analysis.analyzer import ArchitecturalAnalyzer

    analyzer = ArchitecturalAnalyzer(repo)
    analysis = analyzer.analyze_impact(issue.id)

    analysis_data = {
        "directly_affected": [{"id": str(i.id), "title": i.title} for i in analysis.directly_affected],
        "transitively_affected": [{"id": str(i.id), "title": i.title} for i in analysis.transitively_affected],
        "blocked_issues": [{"id": str(i.id), "title": i.title} for i in analysis.blocked_issues],
        "affected_components": analysis.affected_components,
        "risk_level": analysis.risk_level.value,
    }

    mirror = GitHubMirroringService()
    result = mirror.mirror_impact(issue.github_issue_number, analysis_data)
    mirror.close()

    return APIResponse(
        data={"mirrored": True, "comment_url": result.get("html_url")},
        meta=Meta(request_id=None),
    )


@issues_router.post(
    "/issues/{issue_id}/reasoning",
    response_model=APIResponse[IssueResponse],
    summary="Add reasoning log entry",
    description=(
        "Add a reasoning log entry to an issue. "
        "Captures the AI's decision-making process for transparency and auditability."
    ),
    responses={
        404: {"description": "Issue not found"},
    },
)
def add_reasoning_log(
    issue_id: str,
    body: ReasoningLogEntryRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    updated_issue = repo.add_reasoning_log(
        issue_id=issue_id,
        context=body.context,
        reasoning=body.reasoning,
        related_nodes=body.related_nodes,
    )
    return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))


@issues_router.get(
    "/issues/{issue_id}/reasoning",
    response_model=APIResponse[list[ReasoningLogEntryResponse]],
    summary="Get reasoning logs",
    description="Get all reasoning log entries for an issue.",
    responses={
        404: {"description": "Issue not found"},
    },
)
def get_reasoning_logs(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[ReasoningLogEntryResponse]]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    logs = repo.get_reasoning_logs(issue_id)
    log_responses = [
        ReasoningLogEntryResponse(
            id=log.get("id", ""),
            timestamp=log.get("timestamp", ""),
            context=log.get("context", ""),
            reasoning=log.get("reasoning", ""),
            related_nodes=log.get("related_nodes", []),
        )
        for log in logs
    ]
    return APIResponse(data=log_responses, meta=Meta(request_id=None))


@issues_router.patch(
    "/issues/{issue_id}/manifest/todo",
    response_model=APIResponse[IssueResponse],
    summary="Update manifest TODO list",
    description=(
        "Update the agent progress manifest TODO list. "
        "Maintains real-time documentation of sub-tasks with completion status."
    ),
    responses={
        404: {"description": "Issue not found"},
    },
)
def update_manifest_todo(
    issue_id: str,
    body: ManifestTodoRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    todo_list = [{"task": item.task, "completed": str(item.completed)} for item in body.todo]
    updated_issue = repo.update_manifest_todo(issue_id, todo_list)
    return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))


@issues_router.patch(
    "/issues/{issue_id}/manifest/files",
    response_model=APIResponse[IssueResponse],
    summary="Update manifest affected files",
    description=(
        "Update the agent progress manifest with affected files. Tracks created or modified file paths in real-time."
    ),
    responses={
        404: {"description": "Issue not found"},
    },
)
def update_manifest_files(
    issue_id: str,
    body: ManifestFilesRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    updated_issue = repo.update_manifest_files(issue_id, body.files)
    return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))


@issues_router.patch(
    "/issues/{issue_id}/manifest/notes",
    response_model=APIResponse[IssueResponse],
    summary="Update manifest technical debt notes",
    description=(
        "Update the agent progress manifest with technical debt notes. Records observations made during implementation."
    ),
    responses={
        404: {"description": "Issue not found"},
    },
)
def update_manifest_notes(
    issue_id: str,
    body: ManifestNotesRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    updated_issue = repo.update_manifest_notes(issue_id, body.notes)
    return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))


@issues_router.get(
    "/issues/{issue_id}/manifest",
    response_model=APIResponse[ManifestResponse],
    summary="Get manifest",
    description="Get the full agent progress manifest for an issue.",
    responses={
        404: {"description": "Issue not found"},
    },
)
def get_manifest(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ManifestResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    manifest = repo.get_manifest(issue_id)
    return APIResponse(
        data=ManifestResponse(
            todo=manifest.get("todo", []),
            files=manifest.get("files", []),
            notes=manifest.get("notes", []),
        ),
        meta=Meta(request_id=None),
    )


@issues_router.post(
    "/issues/{issue_id}/agent/start",
    response_model=APIResponse[IssueResponse],
    summary="Start agent work",
    description="Start agent work on an issue. Requires agent_working=false.",
    responses={
        404: {"description": "Issue not found"},
        409: {"description": "Agent is already working on this issue"},
    },
)
def start_agent_work(
    issue_id: str,
    body: AgentStartRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    try:
        issue = repo.get_issue(issue_id)
        if issue is None:
            raise IssueNotFoundError(issue_id)

        if hasattr(issue, "agent_working") and issue.agent_working:
            from fastapi import HTTPException

            raise HTTPException(
                status_code=409,
                detail=f"Agent is already working on issue {issue_id}",
            )

        updated_issue = repo.start_agent_work(issue_id, body.agent_id)
        return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))
    except ValueError as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=409, detail=str(e))


@issues_router.post(
    "/issues/{issue_id}/agent/finish",
    response_model=APIResponse[IssueResponse],
    summary="Finish agent work",
    description="Finish agent work on an issue. Requires agent_working=true.",
    responses={
        404: {"description": "Issue not found"},
        409: {"description": "Agent is not working on this issue"},
    },
)
def finish_agent_work(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    try:
        issue = repo.get_issue(issue_id)
        if issue is None:
            raise IssueNotFoundError(issue_id)

        updated_issue = repo.finish_agent_work(issue_id)
        return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))
    except ValueError as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=409, detail=str(e))


@issues_router.post(
    "/issues/{issue_id}/agent/heartbeat",
    response_model=APIResponse[IssueResponse],
    summary="Agent heartbeat to renew lock lease",
    description="Agents must call this periodically (e.g., every 5 min) to keep their lock. Updates locked_until timestamp.",
)
def agent_heartbeat(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[IssueResponse]:
    from datetime import datetime, timezone
    from fastapi import HTTPException

    try:
        issue = repo.get_issue(issue_id)
        if issue is None:
            raise IssueNotFoundError(issue_id)

        if not issue.agent_working:
            raise HTTPException(status_code=409, detail="No agent is working on this issue")

        locked_until = issue.locked_until
        if locked_until is None:
            from datetime import timedelta
            locked_until = datetime.now(timezone.utc) + timedelta(minutes=5)

        repo.update_issue(issue_id, {"locked_until": locked_until.isoformat()})
        updated_issue = repo.get_issue(issue_id)
        return APIResponse(data=_issue_to_response(updated_issue), meta=Meta(request_id=None))
    except ValueError as e:
        raise HTTPException(status_code=409, detail=str(e))


@issues_router.get(
    "/issues/{issue_id}/agent/status",
    response_model=APIResponse[AgentStatusResponse],
    summary="Get agent status",
    description="Get agent work status for an issue.",
    responses={
        404: {"description": "Issue not found"},
    },
)
def get_agent_status(
    issue_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[AgentStatusResponse]:
    issue = repo.get_issue(issue_id)
    if issue is None:
        raise IssueNotFoundError(issue_id)

    status = repo.get_agent_status(issue_id)
    return APIResponse(
        data=AgentStatusResponse(
            agent_working=status.get("agent_working", False),
            agent_started_at=status.get("agent_started_at"),
            agent_finished_at=status.get("agent_finished_at"),
            agent_id=status.get("agent_id"),
        ),
        meta=Meta(request_id=None),
    )
