"""API router for labels.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Label router
# ---------------------------------------------------------------------------

label_router = APIRouter()


@label_router.get(
    "/labels",
    response_model=APIResponse[list[dict]],
    summary="List all labels",
    description="List all labels synced from GitHub or created in Tasker.",
)
def list_labels(
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[dict]]:
    labels = repo.get_all_labels() if hasattr(repo, "get_all_labels") else []
    return APIResponse(data=labels, meta=Meta(request_id=None))


@label_router.post(
    "/labels/sync",
    response_model=APIResponse[dict],
    summary="Sync labels from GitHub",
    description="Force sync labels from GitHub repository to Neo4j.",
)
def sync_labels(
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    from socialseed_tasker.infrastructure.github_adapter import GitHubAdapter

    try:
        adapter = GitHubAdapter()
        synced = repo.sync_labels_from_github(adapter)
        adapter.close()
        return APIResponse(data={"synced": synced}, meta=Meta(request_id=None))
    except Exception as e:
        from fastapi import HTTPException

        raise HTTPException(status_code=500, detail=str(e))


@label_router.get(
    "/issues",
    response_model=APIResponse[list[IssueResponse]],
    summary="List issues by labels",
    description="List issues with optional filtering by labels, status, component, or project.",
    operation_id="list_issues_by_labels",
)
def list_issues(
    labels: str | None = Query(None, description="Filter by comma-separated labels"),
    status: str | None = Query(None, description="Filter by status"),
    component_id: str | None = Query(None, description="Filter by component"),
    project: str | None = Query(None, description="Filter by project"),
    page: int = Query(1, ge=1, description="Page number (starts at 1, default: 1)"),
    limit: int = Query(50, ge=1, le=100, description="Items per page (default: 50, max: 100)"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[IssueResponse]]:
    label_list = [label.strip() for label in labels.split(",")] if labels else []

    if label_list and hasattr(repo, "get_issues_by_labels"):
        issues = repo.get_issues_by_labels(label_list)
    else:
        issues = repo.list_issues(
            component_id=component_id,
            status=status,
            project=project,
        )

    start = (page - 1) * limit
    end = start + limit
    paginated = issues[start:end]

    return APIResponse(
        data=[_issue_to_response(i) for i in paginated],
        meta=Meta(request_id=None),
    )
