"""API router for objective.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Objective router
# ---------------------------------------------------------------------------

objective_router = APIRouter()


@objective_router.post(
    "/objectives",
    response_model=APIResponse[dict],
    status_code=201,
    summary="Create an objective",
    description="Create a new objective (OKR).",
)
def create_objective(
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    from uuid import uuid4

    objective = Objective(
        id=uuid4(),
        name=body.get("name", ""),
        description=body.get("description", ""),
        status=ObjectiveStatus(body.get("status", "OPEN")),
        quarter=body.get("quarter", ""),
    )
    repo.create_objective(objective)
    return APIResponse(
        data={"id": str(objective.id), "name": objective.name},
        meta=Meta(request_id=None),
    )


@objective_router.get(
    "/objectives",
    response_model=APIResponse[list],
    summary="List objectives",
    description="List all objectives in the system.",
)
def list_objectives(repo: TaskRepositoryInterface = Depends(get_repo)):
    objectives = repo.list_objectives()
    return APIResponse(
        data=[{"id": str(o.id), "name": o.name, "status": o.status.value, "quarter": o.quarter} for o in objectives],
        meta=Meta(request_id=None),
    )


@objective_router.get(
    "/objectives/{objective_id}",
    response_model=APIResponse[dict],
    summary="Get an objective",
    description="Get details of a specific objective.",
)
def get_objective(objective_id: str, repo: TaskRepositoryInterface = Depends(get_repo)):
    objective = repo.get_objective(objective_id)
    if objective is None:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="Objective not found")
    return APIResponse(
        data={
            "id": str(objective.id),
            "name": objective.name,
            "description": objective.description,
            "status": objective.status.value,
            "quarter": objective.quarter,
        },
        meta=Meta(request_id=None),
    )


@objective_router.delete(
    "/objectives/{objective_id}",
    response_model=APIResponse[dict],
    summary="Delete an objective",
    description="Delete an objective.",
)
def delete_objective(objective_id: str, repo: TaskRepositoryInterface = Depends(get_repo)):
    repo.delete_objective(objective_id)
    return APIResponse(data={"deleted": objective_id}, meta=Meta(request_id=None))


@objective_router.patch(
    "/objectives/{objective_id}",
    response_model=APIResponse[dict],
    summary="Update an objective",
    description="Update an objective.",
)
def update_objective(
    objective_id: str,
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
):
    repo.update_objective(objective_id, body)
    return APIResponse(data={"updated": objective_id}, meta=Meta(request_id=None))


@objective_router.post(
    "/objectives/{objective_id}/epics",
    response_model=APIResponse[dict],
    summary="Link epics to objective",
    description="Link multiple epics to an objective.",
)
def link_epics_to_objective(
    objective_id: str,
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
):

    epic_ids = body.get("epic_ids", [])
    for epic_id in epic_ids:
        repo.link_epic_to_objective(epic_id, objective_id)
    return APIResponse(
        data={"objective_id": objective_id, "linked_epics": len(epic_ids)},
        meta=Meta(request_id=None),
    )

