"""API router for policy.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.core.project_analysis.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.core.task_management.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.core.task_management.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.entrypoints.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.entrypoints.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Policy router
# ---------------------------------------------------------------------------
# Policy router
# ---------------------------------------------------------------------------

policy_router = APIRouter()


@policy_router.post(
    "/policies/validate",
    response_model=APIResponse[PolicyValidationResponse],
    summary="Validate action against policies",
    description="Check if an action would violate any architectural rules without actually performing the action.",
)
def validate_policy(
    body: PolicyValidationRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
    request: Request = None,
) -> APIResponse[PolicyValidationResponse]:
    from uuid import UUID

    from socialseed_tasker.core.project_analysis.analyzer import ArchitecturalAnalyzer
    from socialseed_tasker.core.task_management.entities import Issue, IssuePriority, IssueStatus

    enforcement_mode = "warn"
    if request and hasattr(request.app.state, "config"):
        enforcement_mode = getattr(request.app.state.config, "policy_enforcement_mode", "warn")

    analyzer = ArchitecturalAnalyzer(repo)
    violations = []

    if body.action_type == "create_issue" and body.issue_data:
        issue_data = body.issue_data
        issue = Issue(
            id=UUID(),
            title=issue_data.get("title", ""),
            description=issue_data.get("description", ""),
            status=IssueStatus.OPEN,
            priority=IssuePriority(issue_data.get("priority", "MEDIUM")),
            component_id=UUID(issue_data.get("component_id", "")),
            labels=issue_data.get("labels", []),
        )
        result = analyzer.validate_issue_creation(issue)
        for v in result.violations:
            violations.append(
                PolicyViolationResponse(
                    rule_id=str(v.rule_id),
                    rule_name=v.rule_name,
                    severity=v.severity.value,
                    message=v.message,
                    suggestion=v.suggestion,
                )
            )
    elif body.action_type == "add_dependency" and body.dependency_data:
        dep_data = body.dependency_data
        issue_id = dep_data.get("issue_id", "")
        depends_on_id = dep_data.get("depends_on_id", "")
        result = analyzer.validate_dependency(issue_id, depends_on_id)
        for v in result.violations:
            violations.append(
                PolicyViolationResponse(
                    rule_id=str(v.rule_id),
                    rule_name=v.rule_name,
                    severity=v.severity.value,
                    message=v.message,
                    suggestion=v.suggestion,
                )
            )

    has_errors = any(v.severity == "ERROR" for v in violations)

    return APIResponse(
        data=PolicyValidationResponse(
            is_valid=not has_errors or enforcement_mode == "disabled",
            violations=violations,
            enforcement_mode=enforcement_mode,
        ),
        meta=Meta(request_id=None),
    )


@policy_router.get(
    "/policies/rules",
    response_model=APIResponse[list[dict]],
    summary="Get active policy rules",
    description="List all active architectural rules.",
)
def get_policy_rules(
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[dict]]:
    from socialseed_tasker.core.project_analysis.analyzer import ArchitecturalAnalyzer

    analyzer = ArchitecturalAnalyzer(repo)
    rules = analyzer.list_rules()

    rules_data = [
        {
            "id": str(r.id),
            "name": r.name,
            "description": r.description,
            "rule_type": r.rule_type.value,
            "severity": r.severity.value,
            "is_active": r.is_active,
        }
        for r in rules
    ]

    return APIResponse(data=rules_data, meta=Meta(request_id=None))


@policy_router.get(
    "/policies/component/{component_id}",
    response_model=APIResponse[list[dict]],
    summary="Get policies for component",
    description="Get all policies that apply to a specific component.",
)
def get_policies_for_component(
    component_id: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[dict]]:
    from socialseed_tasker.core.project_analysis.analyzer import ArchitecturalAnalyzer

    analyzer = ArchitecturalAnalyzer(repo)
    rules = analyzer.list_rules()

    policies_data = [
        {
            "id": str(r.id),
            "name": r.name,
            "description": r.description,
            "severity": r.severity.value if hasattr(r.severity, 'value') else str(r.severity),
            "rule_type": r.rule_type.value if hasattr(r.rule_type, 'value') else str(r.rule_type),
            "is_active": r.is_active,
        }
        for r in rules
    ]

    return APIResponse(data=policies_data, meta=Meta(request_id=None))


# In-memory policy storage for demonstration
_policy_engine: dict[str, Any] = {"policies": []}


@policy_router.post(
    "/policies",
    response_model=APIResponse[PolicyResponse],
    status_code=201,
    summary="Create a policy",
    description="Create a new policy with rules for architectural governance.",
)
def create_policy(
    body: PolicyCreateRequest,
    request: Request,
) -> APIResponse[PolicyResponse]:
    from socialseed_tasker.core.project_analysis.policy import Policy, PolicyRule, PolicyRuleType, PolicyTargetScope, PolicySeverity
    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository
    from socialseed_tasker.storage.graph_database.rag_repository import RAGRepository
    from uuid import UUID

    driver = request.app.state.driver
    policy_repo = PolicyRepository(driver)
    rag_repo = RAGRepository(driver)

    rules = []
    for rule_req in body.rules:
        rules.append(
            PolicyRule(
                rule_type=PolicyRuleType(rule_req.rule_type),
                from_pattern=rule_req.from_pattern,
                to_pattern=rule_req.to_pattern,
                max_depth=rule_req.max_depth,
                description=rule_req.description,
            )
        )

    policy = Policy(
        name=body.name,
        description=body.description,
        severity=PolicySeverity(body.severity) if hasattr(body, "severity") and body.severity else PolicySeverity.WARNING,
        rules=rules,
        target_scope=PolicyTargetScope(body.target_scope) if body.target_scope else PolicyTargetScope.COMPONENT,
        logic_definition=body.logic_definition,
        remediation_strategy=body.remediation_strategy,
        autofix_template=body.autofix_template,
        is_active=body.is_active,
    )

    policy_repo.create_policy(policy)
    
    # Link to project if provided
    if hasattr(body, "project_id") and body.project_id:
        policy_repo.link_policy_to_project(str(policy.id), body.project_id)
    
    # Index for RAG
    content = f"Policy: {policy.name}\nDescription: {policy.description}\nScope: {policy.target_scope.value}\nRules: {policy.rules}"
    rag_repo.create_native_embedding("policy", str(policy.id), content)

    return APIResponse(
        data=PolicyResponse(
            id=str(policy.id),
            name=policy.name,
            description=policy.description,
            rules=[
                {"rule_type": r.rule_type.value, "from_pattern": r.from_pattern, "to_pattern": r.to_pattern}
                for r in policy.rules
            ],
            target_scope=policy.target_scope.value,
            logic_definition=policy.logic_definition,
            remediation_strategy=policy.remediation_strategy,
            autofix_template=policy.autofix_template,
            is_active=policy.is_active,
            created_at=policy.created_at,
            updated_at=policy.updated_at,
        ),
        meta=Meta(request_id=None),
    )


@policy_router.get(
    "/policies",
    response_model=APIResponse[list[PolicyResponse]],
    summary="List policies",
    description="List all policies.",
)
def list_policies(
    request: Request,
    name: str = None,
) -> APIResponse[list[PolicyResponse]]:
    from socialseed_tasker.storage.graph_database.policy_repository import PolicyRepository
    
    driver = request.app.state.driver
    policy_repo = PolicyRepository(driver)
    
    if name:
        policy = policy_repo.get_policy_by_name(name)
        policies = [policy] if policy else []
    else:
        policies = policy_repo.list_policies()
        
    return APIResponse(
        data=[
            PolicyResponse(
                id=str(p.id),
                name=p.name,
                description=p.description,
                rules=[
                    {"rule_type": r.rule_type.value, "from_pattern": r.from_pattern, "to_pattern": r.to_pattern}
                    for r in p.rules
                ],
                target_scope=p.target_scope.value,
                logic_definition=p.logic_definition,
                remediation_strategy=p.remediation_strategy,
                autofix_template=p.autofix_template,
                is_active=p.is_active,
                created_at=p.created_at,
                updated_at=p.updated_at,
            )
            for p in policies
        ],
        meta=Meta(request_id=None),
    )


@policy_router.get(
    "/policies/{policy_id}",
    response_model=APIResponse[PolicyResponse],
    summary="Get a policy",
    description="Get a policy by ID.",
)
def get_policy(policy_id: str) -> APIResponse[PolicyResponse]:

    policies = _policy_engine.get("policies", [])
    for p in policies:
        if str(p.id) == policy_id:
            return APIResponse(
                data=PolicyResponse(
                    id=str(p.id),
                    name=p.name,
                    description=p.description,
                    rules=[
                        {"rule_type": r.rule_type.value, "from_pattern": r.from_pattern, "to_pattern": r.to_pattern}
                        for r in p.rules
                    ],
                    is_active=p.is_active,
                    created_at=p.created_at,
                    updated_at=p.updated_at,
                ),
                meta=Meta(request_id=None),
            )

    from fastapi import HTTPException

    raise HTTPException(status_code=404, detail=f"Policy {policy_id} not found")


@policy_router.delete(
    "/policies/{policy_id}",
    response_model=APIResponse[dict],
    summary="Delete a policy",
    description="Delete a policy by ID.",
)
def delete_policy(policy_id: str) -> APIResponse[dict]:
    policies = _policy_engine.get("policies", [])
    _policy_engine["policies"] = [p for p in policies if str(p.id) != policy_id]
    return APIResponse(data={"deleted": policy_id}, meta=Meta(request_id=None))


@policy_router.post(
    "/policies/dry-run",
    response_model=APIResponse[PolicyValidationResponse],
    summary="Dry-run validation",
    description="Validate an action against policies without actually executing it.",
)
def dry_run_policy(
    body: PolicyValidationRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[PolicyValidationResponse]:
    from socialseed_tasker.core.project_analysis.policy import PolicyEngine

    violations = []

    if body.action_type == "add_dependency" and body.dependency_data:
        dep_data = body.dependency_data
        issue_id = dep_data.get("issue_id", "")
        depends_on_id = dep_data.get("depends_on_id", "")

        if issue_id and depends_on_id:
            issue = repo.get_issue(issue_id)
            target = repo.get_issue(depends_on_id)

            if issue and target:
                from_component = repo.get_component(str(issue.component_id))
                to_component = repo.get_component(str(target.component_id))

                policies = _policy_engine.get("policies", [])
                engine = PolicyEngine(policies)

                result = engine.validate_dependency(
                    from_component_name=from_component.name if from_component else "",
                    from_component_type=from_component.project if from_component else "",
                    from_labels=issue.labels,
                    to_component_name=to_component.name if to_component else "",
                    to_component_type=to_component.project if to_component else "",
                    to_labels=target.labels,
                )

                for v in result.violations:
                    violations.append(
                        PolicyViolationResponse(
                            rule_id=str(v.policy_id),
                            rule_name=v.policy_name,
                            severity="ERROR",
                            message=v.message,
                            suggestion=v.suggestion,
                        )
                    )

    return APIResponse(
        data=PolicyValidationResponse(
            is_valid=len(violations) == 0,
            violations=violations,
            enforcement_mode="dry-run",
        ),
        meta=Meta(request_id=None),
    )
