"""API router for project.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure import neo4j_queries as queries
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Project router
# ---------------------------------------------------------------------------

project_router = APIRouter()


@project_router.get(
    "/projects",
    response_model=APIResponse[list[str]],
    summary="List all projects",
    description="List all unique project names in the system.",
)
def list_all_projects(
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list[str]]:
    projects = repo.list_projects()
    return APIResponse(data=projects, meta=Meta(request_id=None))


@project_router.get(
    "/projects/all",
    response_model=APIResponse[list[ProjectResponse]],
    summary="List all projects with details",
    description="Returns all projects with their complete details.",
)
def list_all_projects_detailed(
    request: Request,
) -> APIResponse[list[ProjectResponse]]:
    from socialseed_tasker.infrastructure import neo4j_queries

    driver = getattr(request.app.state, "driver", None)
    if driver is None:
        try:
            from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
            driver = get_neo4j_driver()
        except Exception:
            driver = None

    if driver is None:
        return APIResponse(data=[], meta=Meta(request_id=None))

    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"

    with actual_driver.session(database=db) as session:
        result = session.run(queries.LIST_PROJECT_NODES)
        projects = []
        for record in result:
            p = record["p"]
            project_data = {
                "id": p.get("id"),
                "name": p.get("name"),
                "slug": p.get("slug"),
                "description": p.get("description", ""),
                "repositoryUrl": p.get("repositoryUrl", ""),
                "basePackage": p.get("basePackage", ""),
                "visibility": p.get("visibility", "PUBLIC"),
                "status": p.get("status", "DEVELOPMENT"),
                "techStack": p.get("techStack", []),
                "mainStack": p.get("mainStack", []),
                "architectureStyle": p.get("architectureStyle", "api-first"),
                "version": p.get("version", "0.1.0"),
                "conventionsUrl": p.get("conventionsUrl", ""),
                "globalStatus": p.get("globalStatus", "DEVELOPMENT"),
                "createdAt": p.get("createdAt"),
                "updatedAt": p.get("updatedAt"),
            }
            projects.append(ProjectResponse(**project_data))
        return APIResponse(data=projects, meta=Meta(request_id=None))


@project_router.get(
    "/projects/current",
    response_model=APIResponse[ProjectResponse | None],
    summary="Get current/active project",
    description="Returns the most recently created project as the current one.",
)
def get_current_project(
    request: Request,
) -> APIResponse[ProjectResponse | None]:
    from socialseed_tasker.infrastructure import neo4j_queries

    driver = getattr(request.app.state, "driver", None)
    if driver is None:
        try:
            from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
            driver = get_neo4j_driver()
        except Exception:
            driver = None

    if driver is None:
        return APIResponse(data=None, meta=Meta(request_id=None))

    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"

    with actual_driver.session(database=db) as session:
        result = session.run(queries.GET_DEFAULT_PROJECT)
        record = result.single()

        if not record:
            return APIResponse(data=None, meta=Meta(request_id=None))

        p = record["p"]
        project_data = {
            "id": p.get("id"),
            "name": p.get("name"),
            "slug": p.get("slug"),
            "description": p.get("description", ""),
            "repositoryUrl": p.get("repositoryUrl", ""),
            "basePackage": p.get("basePackage", ""),
            "visibility": p.get("visibility", "PUBLIC"),
            "status": p.get("status", "DEVELOPMENT"),
            "techStack": p.get("techStack", []),
            "mainStack": p.get("mainStack", []),
            "architectureStyle": p.get("architectureStyle", "api-first"),
            "version": p.get("version", "0.1.0"),
            "conventionsUrl": p.get("conventionsUrl", ""),
            "globalStatus": p.get("globalStatus", "DEVELOPMENT"),
            "createdAt": p.get("createdAt"),
            "updatedAt": p.get("updatedAt"),
        }
        return APIResponse(data=ProjectResponse(**project_data), meta=Meta(request_id=None))


@project_router.get(
    "/projects/{project_id}",
    response_model=APIResponse[ProjectResponse | None],
    summary="Get project by ID or slug",
    description="Returns a specific project by its ID or slug.",
)
def get_project_by_id(
    request: Request,
    project_id: str,
) -> APIResponse[ProjectResponse | None]:
    from socialseed_tasker.infrastructure import neo4j_queries

    driver = getattr(request.app.state, "driver", None)
    if driver is None:
        try:
            from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
            driver = get_neo4j_driver()
        except Exception:
            driver = None

    if driver is None:
        return APIResponse(data=None, meta=Meta(request_id=None))

    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"

    with actual_driver.session(database=db) as session:
        result = session.run(queries.GET_PROJECT_BY_ID, projectId=project_id)
        record = result.single()

        if not record:
            result = session.run(queries.GET_PROJECT_BY_SLUG, slug=project_id)
            record = result.single()

        if not record:
            return APIResponse(data=None, meta=Meta(request_id=None))

        p = record["p"]
        project_data = {
            "id": p.get("id"),
            "name": p.get("name"),
            "slug": p.get("slug"),
            "description": p.get("description", ""),
            "repositoryUrl": p.get("repositoryUrl", ""),
            "basePackage": p.get("basePackage", ""),
            "visibility": p.get("visibility", "PUBLIC"),
            "status": p.get("status", "DEVELOPMENT"),
            "techStack": p.get("techStack", []),
            "mainStack": p.get("mainStack", []),
            "architectureStyle": p.get("architectureStyle", "api-first"),
            "version": p.get("version", "0.1.0"),
            "conventionsUrl": p.get("conventionsUrl", ""),
            "globalStatus": p.get("globalStatus", "DEVELOPMENT"),
            "createdAt": p.get("createdAt"),
            "updatedAt": p.get("updatedAt"),
        }
        return APIResponse(data=ProjectResponse(**project_data), meta=Meta(request_id=None))


@project_router.post(
    "/projects",
    response_model=APIResponse[dict],
    status_code=201,
    summary="Create or get the single project",
    description="Tasker supports only ONE project. If one exists, it returns the existing one. If not, it creates it.",
)
def create_project(
    request: Request,
    body: ProjectCreateRequest,
) -> APIResponse[dict]:
    from fastapi import HTTPException
    from socialseed_tasker.infrastructure import neo4j_queries
    from datetime import datetime, timezone

    driver = getattr(request.app.state, "driver", None)
    if driver is None:
        try:
            from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
            driver = get_neo4j_driver()
        except Exception:
            driver = None
    
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    
    now = datetime.now(timezone.utc).isoformat()
    
    with actual_driver.session(database=db) as session:
        count_result = session.run(queries.COUNT_PROJECTS)
        count_record = count_result.single()
        existing_count = count_record["count"] if count_record else 0
        
        if existing_count > 0:
            result = session.run(queries.GET_DEFAULT_PROJECT)
            record = result.single()
            if record:
                p = record["p"]
                return APIResponse(
                    data={
                        "status": "exists",
                        "message": "A project already exists. Tasker supports only one project.",
                        "project": {
                            "id": p.get("id"),
                            "name": p.get("name"),
                            "slug": p.get("slug"),
                        }
                    },
                    meta=Meta(request_id=None),
                )
        
        project_id = body.id or body.name.lower().replace(" ", "-")
        slug = body.slug or body.name.lower().replace(" ", "-")
        session.run(
            queries.GET_OR_CREATE_SINGLE_PROJECT,
            id=project_id,
            slug=slug,
            name=body.name,
            description=body.description,
            repositoryUrl=body.repositoryUrl,
            basePackage=body.basePackage,
            visibility=body.visibility,
            status=body.status,
            techStack=body.techStack,
            mainStack=body.mainStack,
            architectureStyle=body.architectureStyle,
            version=body.version,
            conventionsUrl=body.conventionsUrl,
            conventionsRules=body.conventionsRules,
            lastFullScan=now,
            globalStatus=body.globalStatus,
            createdAt=now,
            updatedAt=now,
        )
    
    return APIResponse(data={"status": "created", "id": project_id}, meta=Meta(request_id=None))


@project_router.post(
    "/users",
    response_model=APIResponse[dict],
    status_code=201,
    summary="Create a new user",
    description="Create a new user node in the graph and link to project.",
)
def create_user(
    body: UserCreateRequest,
    project_id: str = Query(..., description="Project ID to link the user to"),
) -> APIResponse[dict]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    import uuid
    from datetime import datetime, timezone

    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    
    user_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()
    
    with actual_driver.session(database=db) as session:
        session.run(
            """
            MERGE (u:User {username: $username})
            ON CREATE SET u.id = $id, u.email = $email, u.role = $role, 
                          u.githubHandle = $github_handle, u.preferences = $preferences,
                          u.createdAt = $now, u.updatedAt = $now
            WITH u
            MATCH (p:Project {id: $project_id})
            MERGE (u)-[:MANAGES]->(p)
            """,
            id=user_id,
            username=body.username,
            email=body.email,
            role=body.role,
            github_handle=body.github_handle,
            preferences=body.preferences,
            project_id=project_id,
            now=now,
        )
    
    return APIResponse(data={"status": "created", "id": user_id}, meta=Meta(request_id=None))


@project_router.get(
    "/projects/{project_name}/summary",
    response_model=APIResponse[ProjectSummaryResponse],
    summary="Get project summary",
    description="Get an aggregated overview of a project including issue counts, dependency health, and critical path.",
)
def get_project_summary(
    project_name: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[ProjectSummaryResponse]:
    components = repo.list_components(project=project_name)
    all_issues = repo.list_issues(project=project_name)

    by_status: dict[str, int] = {}
    by_priority: dict[str, int] = {}

    for issue in all_issues:
        status = issue.status.value
        priority = issue.priority.value
        by_status[status] = by_status.get(status, 0) + 1
        by_priority[priority] = by_priority.get(priority, 0) + 1

    total_issues = sum(by_status.values())

    blocked_issues = get_blocked_issues_action(repo)
    blocked_filtered = [i for i in blocked_issues if any(str(i.component_id) == str(c.id) for c in components)]
    workable_issues = get_workable_issues_action(repo, component_id=None)
    workable_filtered = [i for i in workable_issues if any(str(i.component_id) == str(c.id) for c in components)]

    dependency_health = 0.0
    if total_issues > 0:
        issues_with_deps = sum(1 for i in all_issues if i.dependencies)
        if issues_with_deps > 0:
            closed_deps = sum(
                1
                for i in all_issues
                if i.dependencies
                and all(
                    next((d for d in all_issues if str(d.id) == str(dep_id) and d.status.value == "CLOSED"), None)
                    for dep_id in i.dependencies
                )
            )
            dependency_health = (closed_deps / issues_with_deps) * 100

    component_blocked_counts: dict[str, int] = {}
    for issue in blocked_filtered:
        comp_id = str(issue.component_id)
        component_blocked_counts[comp_id] = component_blocked_counts.get(comp_id, 0) + 1

    top_blocked = sorted(component_blocked_counts.items(), key=lambda x: x[1], reverse=True)[:3]
    top_blocked_components = []
    for comp_id, count in top_blocked:
        comp = repo.get_component(comp_id)
        if comp:
            top_blocked_components.append({comp.name: count})

    critical_path_length = 0
    for issue in all_issues:
        chain = get_dependency_chain_action(repo, str(issue.id))
        if len(chain) > critical_path_length:
            critical_path_length = len(chain)

    return APIResponse(
        data=ProjectSummaryResponse(
            project=project_name,
            total_issues=total_issues,
            by_status=by_status,
            by_priority=by_priority,
            components_count=len(components),
            blocked_issues_count=len(blocked_filtered),
            workable_issues_count=len(workable_filtered),
            dependency_health=round(dependency_health, 1),
            top_blocked_components=top_blocked_components,
            critical_path_length=critical_path_length,
        ),
        meta=Meta(request_id=None),
    )


@project_router.post(
    "/projects/{project_id}/agents/{agent_id}",
    response_model=APIResponse[dict],
    summary="Assign agent to project",
    description="Create (Project)-[:ASSIGNED_TO]->(Agent) relationship.",
)
def assign_agent_to_project(
    project_id: str,
    agent_id: str,
) -> APIResponse[dict]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        session.run(
            queries.PROJECT_ASSIGN_AGENT,
            project_id=project_id,
            agent_id=agent_id,
        )
    return APIResponse(data={"status": "assigned"}, meta=Meta(request_id=None))


@project_router.delete(
    "/projects/{project_id}/agents/{agent_id}",
    response_model=APIResponse[dict],
    summary="Remove agent from project",
    description="Remove (Project)-[:ASSIGNED_TO]->(Agent) relationship.",
)
def remove_agent_from_project(
    project_id: str,
    agent_id: str,
) -> APIResponse[dict]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        session.run(
            queries.PROJECT_REMOVE_AGENT,
            project_id=project_id,
            agent_id=agent_id,
        )
    return APIResponse(data={"status": "removed"}, meta=Meta(request_id=None))


@project_router.get(
    "/projects/{project_id}/agents",
    response_model=APIResponse[list[dict]],
    summary="Get project agents",
    description="Get all agents assigned to a project.",
)
def get_project_agents(
    project_id: str,
) -> APIResponse[list[dict]]:
    from fastapi import HTTPException
    from socialseed_tasker.application.wiring import get_driver as get_neo4j_driver
    from socialseed_tasker.infrastructure import neo4j_queries
    driver = get_neo4j_driver()
    if driver is None:
        raise HTTPException(status_code=503, detail="Neo4j not available")
    actual_driver = driver.driver if hasattr(driver, "driver") else driver
    db = driver.database if hasattr(driver, "database") else "neo4j"
    with actual_driver.session(database=db) as session:
        result = session.run(queries.PROJECT_GET_AGENTS, project_id=project_id)
        agents = [dict(r["a"]) for r in result]
    return APIResponse(data=agents, meta=Meta(request_id=None))
