"""API router for rag.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ==================== RAG (Retrieval-Augmented Generation) ====================

rag_router = APIRouter(tags=["rag"])


def get_rag_driver() -> Any:
    """Get Neo4j driver for RAG."""
    from socialseed_tasker.application.wiring import get_driver

    return get_driver()


@rag_router.post("/rag/index")
async def rag_index(
    source_type: str,
    source_id: str,
    content: str,
    chunking_strategy: str = "paragraph",
    driver: Any = Depends(get_rag_driver),
) -> dict[str, Any]:
    """Index content for RAG semantic search."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_rag_repository import RAGRepository

    repo = RAGRepository(driver)
    repo.create_vector_index()

    chunk_ids = repo.index_text(
        text=content,
        source_type=source_type,
        source_id=source_id,
        chunking_strategy=chunking_strategy,
    )

    return {"indexed": len(chunk_ids), "chunk_ids": chunk_ids}


@rag_router.post("/rag/search")
async def rag_search(
    query: str,
    limit: int = 5,
    threshold: float = 0.7,
    max_content_size: int = Query(8000, ge=100, le=50000, description="Max content chars to return"),
    driver: Any = Depends(get_rag_driver),
) -> dict[str, Any]:
    """Search for similar content using vector similarity.

    Args:
        max_content_size: Maximum characters to return per result (default 8000).
    """
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_rag_repository import RAGRepository

    repo = RAGRepository(driver)
    results = repo.search(query=query, limit=limit, threshold=threshold)

    for r in results:
        content = r.get("content", "")
        if len(content) > max_content_size:
            r["content"] = content[:max_content_size] + "... [truncated]"
        r["content_length"] = len(content)

    return {"results": results, "count": len(results)}


@rag_router.get("/rag/stats")
async def rag_stats(driver: Any = Depends(get_rag_driver)) -> dict[str, Any]:
    """Get RAG index statistics."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_rag_repository import RAGRepository

    repo = RAGRepository(driver)
    stats = repo.get_stats()

    return stats


@rag_router.delete("/rag/{source_type}/{source_id}")
async def rag_delete(
    source_type: str,
    source_id: str,
    driver: Any = Depends(get_rag_driver),
) -> dict[str, str]:
    """Delete RAG embeddings for a source."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_rag_repository import RAGRepository

    repo = RAGRepository(driver)
    repo.delete_by_source(source_type, source_id)

    return {"status": "deleted"}


@rag_router.delete("/rag")
async def rag_clear(driver: Any = Depends(get_rag_driver)) -> dict[str, str]:
    """Clear all RAG embeddings."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_rag_repository import RAGRepository

    repo = RAGRepository(driver)
    repo.clear()

    return {"status": "cleared"}
