"""API router for reasoning.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ==================== AI Reasoning (Agent Decision Logging) ====================

reasoning_router = APIRouter(tags=["reasoning"])


def get_reasoning_driver() -> Any:
    """Get Neo4j driver for reasoning."""
    from socialseed_tasker.application.wiring import get_driver

    return get_driver()


@reasoning_router.post("/reasoning/log")
async def log_reasoning(
    issue_id: str,
    agent_id: str,
    agent_name: str,
    thought: str,
    confidence: float = 0.5,
    alternatives_considered: list[str] | None = None,
    rejected_reasons: list[str] | None = None,
    decision: str | None = None,
    decision_type: str = "unknown",
    context: dict[str, Any] | None = None,
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, Any]:
    """Log agent reasoning for an issue."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.domain.entities import (
        DecisionType,
        ReasoningNode,
    )
    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    try:
        decision_type_enum = DecisionType(decision_type)
    except ValueError:
        decision_type_enum = DecisionType.UNKNOWN

    reasoning = ReasoningNode(
        thought=thought,
        confidence=confidence,
        alternatives_considered=alternatives_considered or [],
        rejected_reasons=rejected_reasons or [],
        decision=decision,
        decision_type=decision_type_enum,
        context=context or {},
    )

    repo = ReasoningRepository(driver)
    reasoning_id = repo.log_reasoning(issue_id, agent_id, agent_name, reasoning)

    return {"id": reasoning_id, "status": "logged"}


@reasoning_router.get("/reasoning/issue/{issue_id}")
async def get_issue_reasoning(
    issue_id: str,
    limit: int = 50,
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, Any]:
    """Get reasoning history for an issue."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    repo = ReasoningRepository(driver)
    reasoning = repo.get_reasoning_by_issue(issue_id, limit)

    return {"reasoning": reasoning, "count": len(reasoning)}


@reasoning_router.get("/reasoning/history")
async def get_reasoning_history(
    limit: int = 100,
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, Any]:
    """Get global reasoning history."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    repo = ReasoningRepository(driver)
    history = repo.get_reasoning_history(limit)

    return {"history": history, "count": len(history)}


@reasoning_router.get("/reasoning/timeline")
async def get_reasoning_timeline(
    limit: int = Query(100, ge=1, le=500, description="Maximum entries"),
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, Any]:
    """Get reasoning history as a timeline for visualization."""
    if not driver:
        return {"error": "Neo4j not connected", "timeline": []}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import ReasoningRepository

    repo = ReasoningRepository(driver)
    history = repo.get_reasoning_history(limit)

    timeline = []
    for entry in history:
        timeline.append({
            "id": entry.get("id"),
            "issue_id": entry.get("issue_id"),
            "agent_name": entry.get("agent_name"),
            "thought": entry.get("thought", "")[:200],
            "decision": entry.get("decision"),
            "confidence": entry.get("confidence"),
            "timestamp": entry.get("created_at"),
            "decision_type": entry.get("decision_type"),
        })

    return {"timeline": timeline, "count": len(timeline)}


@reasoning_router.post("/reasoning/{reasoning_id}/feedback")
async def add_reasoning_feedback(
    reasoning_id: str,
    is_approved: bool,
    feedback_text: str | None = None,
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, Any]:
    """Add human feedback to reasoning."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.domain.entities import ReasoningFeedback
    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    feedback = ReasoningFeedback(
        reasoning_id=reasoning_id,
        is_approved=is_approved,
        feedback_text=feedback_text,
    )

    repo = ReasoningRepository(driver)
    feedback_id = repo.add_feedback(feedback, reasoning_id)

    return {"id": feedback_id, "status": "added"}


@reasoning_router.get("/reasoning/{reasoning_id}/feedback")
async def get_reasoning_feedback(
    reasoning_id: str,
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, Any]:
    """Get feedback for a reasoning."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    repo = ReasoningRepository(driver)
    feedback = repo.get_feedback(reasoning_id)

    return {"feedback": feedback, "count": len(feedback)}


@reasoning_router.get("/reasoning/stats")
async def get_reasoning_stats(driver: Any = Depends(get_reasoning_driver)) -> dict[str, Any]:
    """Get reasoning decision statistics."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    repo = ReasoningRepository(driver)
    stats = repo.get_decision_stats()

    return stats


@reasoning_router.delete("/reasoning/issue/{issue_id}")
async def delete_issue_reasoning(
    issue_id: str,
    driver: Any = Depends(get_reasoning_driver),
) -> dict[str, str]:
    """Delete reasoning for an issue."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    repo = ReasoningRepository(driver)
    repo.delete_by_issue(issue_id)

    return {"status": "deleted"}


@reasoning_router.delete("/reasoning")
async def clear_all_reasoning(driver: Any = Depends(get_reasoning_driver)) -> dict[str, str]:
    """Clear all reasoning data."""
    if not driver:
        return {"error": "Neo4j not connected"}

    from socialseed_tasker.infrastructure.neo4j_reasoning_repository import (
        ReasoningRepository,
    )

    repo = ReasoningRepository(driver)
    repo.clear_all()

    return {"status": "cleared"}
