"""API router for sync.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Sync router
# ---------------------------------------------------------------------------

sync_router = APIRouter()


@sync_router.get(
    "/sync/status",
    response_model=APIResponse[dict],
    summary="Get sync status",
    description="Get current sync status (online/offline, queue size).",
)
def get_sync_status() -> APIResponse[dict]:
    from socialseed_tasker.infrastructure.sync_engine import get_sync_engine

    engine = get_sync_engine()
    engine.check_connectivity()
    status = engine.get_status()

    return APIResponse(data=status, meta=Meta(request_id=None))


@sync_router.get(
    "/sync/queue",
    response_model=APIResponse[list[dict]],
    summary="Get sync queue",
    description="View pending sync queue items.",
)
def get_sync_queue() -> APIResponse[list[dict]]:
    from socialseed_tasker.infrastructure.sync_engine import get_sync_engine

    engine = get_sync_engine()
    queue = engine.get_queue()

    items = [
        {
            "id": str(item.id),
            "operation": item.operation.value,
            "entity_type": item.entity_type.value,
            "entity_id": str(item.entity_id),
            "status": item.status.value,
            "retry_count": item.retry_count,
            "created_at": item.created_at.isoformat(),
        }
        for item in queue
    ]

    return APIResponse(data=items, meta=Meta(request_id=None))


@sync_router.post(
    "/sync/force",
    response_model=APIResponse[dict],
    summary="Force sync",
    description="Force a sync attempt to process the queue.",
)
def force_sync() -> APIResponse[dict]:
    from socialseed_tasker.infrastructure.sync_engine import get_sync_engine

    engine = get_sync_engine()
    engine.check_connectivity()
    result = engine.process_queue()

    return APIResponse(data=result, meta=Meta(request_id=None))
