"""API router for user.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.auth import tokens
from socialseed_tasker.auth.user_store import PostgresUserStore, normalize_user_type
from socialseed_tasker.config.storage import get_database_url
from socialseed_tasker.infrastructure.pg_user_repository import PgUserRepository
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# User router
# ---------------------------------------------------------------------------

user_router = APIRouter()


def _user_to_response(user: "User") -> "UserResponse":  # type: ignore[valid-type]
    """Convert domain User to API response."""
    return UserResponse(
        id=str(user.id),
        username=user.username,
        email=user.email,
        role=user.role.value,
        github_handle=user.github_handle,
        created_at=user.created_at,
        last_login=user.last_login,
        preferences=user.preferences,
    )


def _pg_repository() -> PgUserRepository:
    """PostgreSQL repository for /users reads (issue #558)."""
    database_url = get_database_url()
    if not database_url:
        raise HTTPException(
            status_code=503,
            detail="PostgreSQL not configured: TASKER_DATABASE_URL is not set",
        )
    return PgUserRepository(database_url)


def _pg_store() -> PostgresUserStore:
    """PostgreSQL store for /users writes (issue #559)."""
    database_url = get_database_url()
    if not database_url:
        raise HTTPException(
            status_code=503,
            detail="PostgreSQL not configured: TASKER_DATABASE_URL is not set",
        )
    return PostgresUserStore(database_url)


def _profile_to_response(profile: dict[str, Any]) -> UserResponse:
    """Compose the API response from a composed PostgreSQL profile dict."""
    return UserResponse(
        id=str(profile["id"]),
        username=profile["username"],
        email=profile.get("email"),
        role=profile["role"],
        type=profile.get("type") or "human",
        avatar=profile.get("avatar"),
        skills=list(profile.get("skills") or []),
        model=profile.get("model"),
        specialization=profile.get("specialization"),
        is_active=bool(profile.get("is_active", True)),
        github_handle=profile.get("github_handle"),
        created_at=profile.get("created_at"),
        last_login=profile.get("last_login"),
        preferences=profile.get("preferences"),
    )


def _revoke_user_sessions(request: Request, store: PostgresUserStore, user_id: str) -> None:
    """Force a re-login after an effective role change (issue #561).

    Revokes every Redis/Memory session of the subject plus its active refresh
    JTIs, so the next refresh fails with 401 and the login screen issues a
    JWT carrying the role now stored in PostgreSQL. Best effort: the PUT has
    already succeeded, so any revocation failure is only logged. Users without
    a bcrypt credential (#563 pending) have no password sessions to revoke.
    """
    try:
        if not store.has_password(user_id):
            return
        tokens.revoke_all_for_subject(user_id)
        sessions = getattr(request.app.state, "auth_sessions", None)
        if sessions is not None:
            sessions.delete_all_for_user(user_id)
    except Exception as exc:  # noqa: BLE001 - revocation must never break the update
        logger.warning("session revocation for user %s failed: %s", user_id, exc)


@user_router.post(
    "/users",
    response_model=APIResponse[UserResponse],
    status_code=201,
    summary="Create a new human user",
    description="Create a human user in the PostgreSQL root (issue #559).",
)
def create_user(
    body: UserCreateRequest,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[UserResponse]:
    """Create a human user across ``users``/``human_user``/``user_skills`` (#559)."""
    if normalize_user_type(body.type) != "human":
        raise HTTPException(
            status_code=422,
            detail="only human users can be created via POST /users (agents: /agents/profiles, issue #564)",
        )
    store = _pg_store()
    roles = store.list_role_ids()
    role_key = body.role.strip().upper()
    role_map = {role.upper(): role for role in roles}
    if role_key not in role_map:
        raise HTTPException(
            status_code=422,
            detail=f"invalid role: {body.role!r} (expected one of {', '.join(roles)})",
        )
    try:
        uid = store.create_human_user(
            username=body.username,
            email=body.email,
            role_id=role_map[role_key],
            avatar=body.avatar,
            skills=body.skills,
            is_active=body.is_active,
            github_handle=body.github_handle,
            preferences=body.preferences,
        )
    except ValueError as exc:
        if str(exc) in {"username", "email"}:
            raise HTTPException(status_code=409, detail=f"{exc} already exists") from exc
        raise
    if driver:
        try:
            from socialseed_tasker.infrastructure.neo4j_user_repository import UserRepository

            UserRepository(driver).merge_user(uid, body.username, body.email)
        except Exception as exc:  # noqa: BLE001 - projection is best effort (#559)
            logger.warning("neo4j user projection merge failed: %s", exc)
    profile = _pg_repository().get_user(uid)
    if not profile:
        raise HTTPException(status_code=500, detail="created user could not be read back")
    return APIResponse(data=_profile_to_response(profile), meta=Meta(request_id=None))


@user_router.get(
    "/users/{user_id}",
    response_model=APIResponse[UserResponse],
    summary="Get user by ID",
    description="Get a user by their ID.",
)
def get_user(user_id: str) -> APIResponse[UserResponse]:
    """Get a user by ID (PostgreSQL profile, issue #558)."""
    profile = _pg_repository().get_user(user_id)
    if not profile:
        raise HTTPException(status_code=404, detail="User not found")
    return APIResponse(data=_profile_to_response(profile), meta=Meta(request_id=None))


@user_router.get(
    "/users/email/{email}",
    response_model=APIResponse[UserResponse],
    summary="Get user by email",
    description="Get a user by their email address.",
)
def get_user_by_email(email: str) -> APIResponse[UserResponse]:
    """Get a user by email (PostgreSQL profile, issue #558)."""
    profile = _pg_repository().get_user_by_email(email)
    if not profile:
        raise HTTPException(status_code=404, detail="User not found")
    return APIResponse(data=_profile_to_response(profile), meta=Meta(request_id=None))


@user_router.get(
    "/users",
    response_model=APIResponse[list[UserResponse]],
    summary="List users",
    description="List users, optionally filtered by role.",
)
def list_users(
    role: str | None = Query(None, description="Filter by role"),
    limit: int = Query(50, ge=1, le=100),
) -> APIResponse[list[UserResponse]]:
    """List users from the PostgreSQL root (issue #558)."""
    profiles = _pg_repository().list_users(role=role, limit=limit)
    return APIResponse(
        data=[_profile_to_response(profile) for profile in profiles],
        meta=Meta(request_id=None),
    )


@user_router.put(
    "/users/{user_id}",
    response_model=APIResponse[UserResponse],
    status_code=200,
    summary="Update user",
    description="Update a human user across users/human_user/user_skills (issue #560).",
)
def update_user(
    user_id: str,
    body: UserUpdateRequest,
    request: Request,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[UserResponse]:
    """Update a human user profile in PostgreSQL (issue #560)."""
    if body.type is not None and normalize_user_type(body.type) != "human":
        raise HTTPException(
            status_code=422,
            detail="only human users can be updated via PUT /users/{id} (agents: /agents/profiles, issue #567)",
        )
    store = _pg_store()
    role_id = None
    if body.role is not None:
        roles = store.list_role_ids()
        role_map = {role.upper(): role for role in roles}
        role_key = body.role.strip().upper()
        if role_key not in role_map:
            raise HTTPException(
                status_code=422,
                detail=f"invalid role: {body.role!r} (expected one of {', '.join(roles)})",
            )
        role_id = role_map[role_key]
    profile = _pg_repository().get_user(user_id)
    if not profile:
        raise HTTPException(status_code=404, detail="User not found")
    if profile.get("type") != "human":
        raise HTTPException(
            status_code=422,
            detail="only human users can be updated via PUT /users/{id} (agents: /agents/profiles, issue #567)",
        )
    try:
        updated = store.update_human_user(
            user_id=user_id,
            username=body.username,
            email=body.email,
            role_id=role_id,
            avatar=body.avatar,
            skills=body.skills,
            github_handle=body.github_handle,
            preferences=body.preferences,
            is_active=body.is_active,
        )
    except ValueError as exc:
        if str(exc) in {"username", "email"}:
            raise HTTPException(status_code=409, detail=f"{exc} already exists") from exc
        raise
    if not updated:
        raise HTTPException(status_code=404, detail="User not found")
    if role_id is not None and str(profile.get("role") or "") != role_id:
        _revoke_user_sessions(request, store, user_id)
    if driver:
        try:
            from socialseed_tasker.infrastructure.neo4j_user_repository import UserRepository

            UserRepository(driver).merge_user(
                user_id,
                body.username or str(profile["username"]),
                body.email if body.email is not None else profile.get("email"),
            )
        except Exception as exc:  # noqa: BLE001 - projection is best effort (#560)
            logger.warning("neo4j user projection update failed: %s", exc)
    updated_profile = _pg_repository().get_user(user_id)
    if not updated_profile:
        raise HTTPException(status_code=500, detail="updated user could not be read back")
    return APIResponse(data=_profile_to_response(updated_profile), meta=Meta(request_id=None))


@user_router.delete(
    "/users/{user_id}",
    response_model=APIResponse[dict],
    summary="Delete user",
    description="Delete a user from the system.",
)
def delete_user(
    user_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Delete a user."""
    if not driver:
        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_user_repository import UserRepository

    repo = UserRepository(driver)

    if len(repo.list_users(limit=2)) <= 1:
        raise HTTPException(status_code=409, detail="Cannot delete the last user")

    repo.delete_user(user_id)

    # Best-effort: also drop the PostgreSQL row so the view stays consistent (#558);
    # failures are logged, the Neo4j guard above remains authoritative until #562.
    database_url = get_database_url()
    if database_url:
        try:
            PgUserRepository(database_url).delete_user_row(user_id)
        except Exception as exc:
            logger.warning("postgres row for user %s could not be deleted: %s", user_id, exc)

    return APIResponse(data={"status": "deleted"}, meta=Meta(request_id=None))


@user_router.post(
    "/users/{user_id}/last-login",
    response_model=APIResponse[dict],
    summary="Update last login",
    description="Update the last login timestamp for a user.",
)
def update_user_last_login(
    user_id: str,
    driver: Any = Depends(get_code_graph_driver),
) -> APIResponse[dict]:
    """Update last login timestamp."""
    if not driver:
        from fastapi import HTTPException

        raise HTTPException(status_code=503, detail="Neo4j not connected")

    from socialseed_tasker.infrastructure.neo4j_user_repository import UserRepository

    repo = UserRepository(driver)
    repo.update_last_login(user_id)

    return APIResponse(data={"status": "updated"}, meta=Meta(request_id=None))
