"""API router for webhook.

Generated by refactoring for SOLID compliance with descriptive nomenclature.
"""

from __future__ import annotations

import logging
from typing import Any, TYPE_CHECKING
from uuid import UUID

from fastapi import APIRouter, Depends, Query, Request, Body, HTTPException

from socialseed_tasker.application.analyzer import (
    ComponentImpactAnalysis,
    ImpactAnalysis,
    RootCauseAnalyzer,
    TestFailure,
)
from socialseed_tasker.application.actions import (
    CircularDependencyError,
    ComponentNotFoundError,
    IssueAlreadyClosedError,
    IssueNotFoundError,
    OpenDependenciesError,
    PolicyViolationError,
    TaskRepositoryInterface,
    add_dependency_action,
    close_issue_action,
    create_issue_action,
    get_blocked_issues_action,
    get_dependency_chain_action,
    get_workable_issues_action,
    remove_dependency_action,
    reset_data_action,
)
from socialseed_tasker.domain.entities import (
    Agent,
    AgentRole,
    AgentStatus,
    Component,
    Deployment,
    DeploymentEnvironment,
    Epic,
    EpicStatus,
    Issue,
    IssueStatus,
    Objective,
    ObjectiveStatus,
    User,
    UserRole,
)
from socialseed_tasker.infrastructure.web_api.schemas import (
    AgentRegisterRequest,
    AgentResponse,
    AgentStartRequest,
    AgentStatusResponse,
    AgentUpdateRequest,
    APIResponse,
    BulkDependencyRequest,
    BulkDependencyResponse,
    CausalLinkResponse,
    ComponentCreateRequest,
    ComponentImpactAnalysisResponse,
    ComponentImpactIssueSummary,
    ComponentResponse,
    ConstraintLoadResponse,
    ConstraintResponse,
    ConstraintValidationResponse,
    ConstraintViolationResponse,
    DependencyGraphResponse,
    DependencyRequest,
    DependencyResponse,
    GitHubWebhookLogResponse,
    GitHubWebhookTestResponse,
    ImpactAnalysisResponse,
    ImpactIssueSummary,
    IssueCreateRequest,
    IssueResponse,
    IssueUpdateRequest,
    ManifestFilesRequest,
    ManifestNotesRequest,
    ManifestResponse,
    ManifestTodoRequest,
    Meta,
    PaginatedResponse,
    PaginationMeta,
    PolicyCreateRequest,
    PolicyResponse,
    PolicyValidationRequest,
    PolicyValidationResponse,
    PolicyViolationResponse,
    ProjectSummaryResponse,
    ProjectCreateRequest,
    ProjectResponse,
    ReasoningLogEntryRequest,
    ReasoningLogEntryResponse,
    TestFailureRequest,
    TestFailureWebhookRequest,
    TestFailureWebhookResponse,
    UserCreateRequest,
    UserResponse,
    UserUpdateRequest,
    CommitCreateRequest,
    CommitResponse,
    CommitStatsResponse,
)
from socialseed_tasker.infrastructure.web_api.routers.helpers import (
    retrieve_neo4j_code_graph_driver as get_code_graph_driver,
    get_repository_provider as get_repo,
    resolve_component_identifier_to_uuid as resolve_component_id,
    convert_domain_issue_to_api_response as _issue_to_response,
    convert_domain_component_to_api_response as _component_to_response,
    construct_paginated_api_response as _paginated,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Webhook router
# ---------------------------------------------------------------------------

webhook_router = APIRouter()


@webhook_router.post(
    "/deployments",
    response_model=APIResponse[dict],
    summary="Receive CI/CD deployment events",
    description="Webhook endpoint to receive deployment events from CI/CD systems.",
)
def receive_deployment(
    body: dict,
    repo: TaskRepositoryInterface = Depends(get_repo),
    request: Request = None,
) -> APIResponse[dict]:
    from datetime import datetime, timezone
    from uuid import uuid4

    from socialseed_tasker.domain.entities import Deployment, DeploymentEnvironment

    commit_sha = body.get("commit_sha", "")
    environment = body.get("environment", "DEV")
    issue_ids = body.get("issue_ids", [])
    channel = body.get("channel", "webhook")
    deployed_by = body.get("deployed_by", "ci-cd")

    if not commit_sha:
        from fastapi import HTTPException

        raise HTTPException(status_code=400, detail="commit_sha is required")

    try:
        env_type = DeploymentEnvironment(environment)
    except ValueError:
        env_type = DeploymentEnvironment.DEVELOPMENT

    deployment = Deployment(
        id=uuid4(),
        commit_sha=commit_sha,
        environment_name=env_type,
        deployed_at=datetime.now(timezone.utc),
        issue_ids=issue_ids,
        channel=channel,
        deployed_by=deployed_by,
    )
    repo.create_deployment(deployment)

    return APIResponse(
        data={
            "id": str(deployment.id),
            "commit_sha": deployment.commit_sha,
            "environment": deployment.environment_name.value,
            "deployed_at": deployment.deployed_at.isoformat(),
        },
        meta=Meta(request_id=None),
    )


@webhook_router.get(
    "/deployments",
    response_model=APIResponse[list],
    summary="List deployments",
    description="List deployments, optionally filtered by environment.",
)
def list_deployments(
    environment: str | None = Query(None, description="Filter by environment"),
    limit: int = Query(50, ge=1, le=100, description="Maximum results"),
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[list]:
    deployments = repo.get_deployments(environment_name=environment, limit=limit)
    return APIResponse(data=deployments, meta=Meta(request_id=None))


@webhook_router.get(
    "/deployments/by-commit/{commit_sha}",
    response_model=APIResponse[dict],
    summary="Get deployment by commit",
    description="Get deployment details for a specific commit SHA.",
)
def get_deployment_by_commit(
    commit_sha: str,
    repo: TaskRepositoryInterface = Depends(get_repo),
) -> APIResponse[dict]:
    deployment = repo.get_deployment_by_commit(commit_sha)
    if deployment is None:
        from fastapi import HTTPException

        raise HTTPException(status_code=404, detail="Deployment not found")
    return APIResponse(data=deployment, meta=Meta(request_id=None))


@webhook_router.post(
    "/webhooks/test-failure",
    response_model=APIResponse[TestFailureWebhookResponse],
    summary="Receive test failure events",
    description="Webhook endpoint to receive test failure events from socialseed-e2e.",
)
def receive_test_failure(
    body: TestFailureWebhookRequest,
    repo: TaskRepositoryInterface = Depends(get_repo),
    request: Request = None,
) -> APIResponse[TestFailureWebhookResponse]:
    import os

    webhook_api_key = os.environ.get("TASKER_WEBHOOK_API_KEY", "")
    if webhook_api_key:
        auth_header = request.headers.get("X-API-Key", "") if request else ""
        if not auth_header:
            auth_header = request.headers.get("Authorization", "") if request else ""
            if auth_header.startswith("Bearer "):
                auth_header = auth_header[7:]
        if auth_header != webhook_api_key:
            from fastapi import HTTPException

            raise HTTPException(status_code=401, detail="Invalid API key")

    component_id = None
    test_file = body.test_file
    if test_file:
        parts = test_file.replace("\\", "/").split("/")
        for part in parts:
            if part in ("src", "tests", "test"):
                continue
            if part.endswith(".py"):
                component_name = part.replace(".py", "").replace("test_", "")
                components = repo.list_components()
                for comp in components:
                    if comp.name.lower() == component_name.lower():
                        component_id = str(comp.id)
                        break
                if component_id:
                    break
        if not component_id:
            components = repo.list_components()
            if components:
                component_id = str(components[0].id)

    title = f"Test Failure: {body.test_name}"
    description = f"""## Test Failure Details

**Test Name:** {body.test_name}
**Test File:** {body.test_file}
**Test Type:** {body.test_type}
**Error Message:** {body.error_message}

**Stack Trace:**
```
{body.stack_trace}
```

**Commit:** {body.commit_sha}
**Branch:** {body.branch}
"""

    labels = ["test-failure", "auto-created", body.test_type]

    try:
        issue, warnings = create_issue_action(
            repo,
            title=title,
            component_id=component_id or "default",
            description=description,
            priority="HIGH",
            labels=labels,
        )
        return APIResponse(
            data=TestFailureWebhookResponse(
                issue_id=str(issue.id),
                message=f"Issue created for test failure: {body.test_name}",
                success=True,
            ),
            meta=Meta(request_id=None),
        )
    except ComponentNotFoundError:
        components = repo.list_components()
        if components:
            issue, warnings = create_issue_action(
                repo,
                title=title,
                component_id=str(components[0].id),
                description=description,
                priority="HIGH",
                labels=labels,
            )
            return APIResponse(
                data=TestFailureWebhookResponse(
                    issue_id=str(issue.id),
                    message=f"Issue created for test failure: {body.test_name}",
                    success=True,
                ),
                meta=Meta(request_id=None),
            )
        return APIResponse(
            data=TestFailureWebhookResponse(
                issue_id=None,
                message="No components found to assign issue",
                success=False,
            ),
            meta=Meta(request_id=None),
        )
    except Exception as e:
        return APIResponse(
            data=TestFailureWebhookResponse(
                issue_id=None,
                message=f"Failed to create issue: {str(e)}",
                success=False,
            ),
            meta=Meta(request_id=None),
        )


_github_webhook_logs: list[dict] = []


@webhook_router.post(
    "/webhooks/github",
    response_model=APIResponse[dict],
    summary="Receive GitHub webhook events",
    description="Receive real-time updates from GitHub (issues, comments, labels, milestones).",
)
async def receive_github_webhook(
    repo: TaskRepositoryInterface = Depends(get_repo),
    request: Request = None,
) -> APIResponse[dict]:
    import json
    from datetime import datetime, timezone

    from socialseed_tasker.infrastructure.webhook_validator import get_webhook_validator

    if request is None:
        return APIResponse(
            data={"error": "No request context"},
            meta=Meta(request_id=None),
        )

    validator = get_webhook_validator()
    signature = request.headers.get("X-Hub-Signature-256", "")

    body = await request.body()
    if not validator.validate(body, signature):
        from fastapi import HTTPException

        rejected_logs = validator.get_rejected_log()
        sig_preview = signature[:20] if signature else "none"
        logger.warning(f"Webhook rejected: signature={sig_preview}, rejected_count={len(rejected_logs)}")
        raise HTTPException(status_code=401, detail="Invalid signature")

    event_type = request.headers.get("X-GitHub-Event", "unknown")
    payload = json.loads(body)

    log_entry = {
        "id": str(len(_github_webhook_logs)),
        "event_type": event_type,
        "delivery_status": "received",
        "received_at": datetime.now(timezone.utc).isoformat(),
        "processed_at": None,
        "error": None,
    }

    try:
        if event_type == "issues":
            action = payload.get("action", "")
            _issue = payload.get("issue", {})

            if action in ("opened", "closed", "reopened"):
                pass

        elif event_type == "issue_comment":
            _comment = payload.get("comment", {})

        elif event_type == "label":
            _label = payload.get("label", {})

        elif event_type == "milestone":
            _milestone = payload.get("milestone", {})

        log_entry["delivery_status"] = "processed"
        log_entry["processed_at"] = datetime.now(timezone.utc).isoformat()

    except Exception as e:
        log_entry["delivery_status"] = "error"
        log_entry["error"] = str(e)

    _github_webhook_logs.append(log_entry)
    if len(_github_webhook_logs) > 100:
        _github_webhook_logs.pop(0)

    return APIResponse(
        data={"received": True, "event": event_type},
        meta=Meta(request_id=None),
    )


@webhook_router.get(
    "/webhooks/github/logs",
    response_model=APIResponse[list[GitHubWebhookLogResponse]],
    summary="Get webhook delivery logs",
    description="View GitHub webhook delivery logs for debugging.",
)
def get_webhook_logs() -> APIResponse[list[GitHubWebhookLogResponse]]:
    logs = [
        GitHubWebhookLogResponse(
            id=log["id"],
            event_type=log["event_type"],
            delivery_status=log["delivery_status"],
            received_at=log["received_at"],
            processed_at=log.get("processed_at"),
            error=log.get("error"),
        )
        for log in _github_webhook_logs
    ]
    return APIResponse(data=logs, meta=Meta(request_id=None))


@webhook_router.get(
    "/webhooks/github/test",
    response_model=APIResponse[GitHubWebhookTestResponse],
    summary="Test webhook configuration",
    description="Test webhook configuration and connectivity.",
)
def test_webhook() -> APIResponse[GitHubWebhookTestResponse]:
    from socialseed_tasker.application.secret_manager import get_webhook_secret

    webhook_secret = get_webhook_secret()

    if not webhook_secret:
        return APIResponse(
            data=GitHubWebhookTestResponse(
                success=False,
                message="GITHUB_WEBHOOK_SECRET not configured",
            ),
            meta=Meta(request_id=None),
        )

    return APIResponse(
        data=GitHubWebhookTestResponse(
            success=True,
            message="Webhook configuration valid",
        ),
        meta=Meta(request_id=None),
    )


# In-memory agent storage for swarm coordination
_agents: dict[str, dict] = {}
