"""CLI setup command - boots the Docker stack and points to the Setup Wizard.

Intent: Provide a single 'tasker setup' entry point for first-time installs that
verifies Docker/Docker Compose is available, generates the default '.env' file
and starts the compose stack, printing the web Setup Wizard URL.
Business Value: Removes manual environment editing from the install flow so a
fresh clone (or PyPI install run inside the repository) reaches the wizard in
one command (issue #542).
"""

from __future__ import annotations

import os
import secrets
import shutil
import subprocess
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

DEFAULT_FRONTEND_PORT = 19001
DEFAULT_API_PORT = 8888
DEFAULT_NEO4J_PASSWORD = "neoSocial"
COMPOSE_FILENAMES = ("docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml")

console = Console(
    width=80,
    no_color=None,
    force_terminal=True,
    soft_wrap=False,
)


def find_compose_file(start: Path | None = None) -> Path | None:
    """Walk upwards from *start* (default: CWD) looking for a compose file."""
    current = (start or Path.cwd()).resolve()
    for directory in (current, *current.parents):
        for name in COMPOSE_FILENAMES:
            candidate = directory / name
            if candidate.is_file():
                return candidate
    return None


def check_docker() -> None:
    """Verify the docker binary and the Compose v2 plugin, or abort with exit code 1."""
    if shutil.which("docker") is None:
        console.print("[error]Docker was not found on this system.[/error]")
        console.print("Install Docker Desktop (or Docker Engine + the Compose plugin) and run 'tasker setup' again.")
        raise typer.Exit(code=1)
    if not _compose_available():
        console.print("[error]Docker Compose is not available ('docker compose version' failed).[/error]")
        console.print("Install the Docker Compose v2 plugin and run 'tasker setup' again.")
        raise typer.Exit(code=1)


def _compose_available() -> bool:
    """Return True when `docker compose version` succeeds."""
    try:
        result = subprocess.run(
            ["docker", "compose", "version"],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return result.returncode == 0


def neo4j_volume_exists() -> bool:
    """Return True when a previous run left a Neo4j data volume behind.

    An existing volume keeps the password it was initialized with, so the
    generated '.env' must reuse the default password in that case.
    """
    try:
        result = subprocess.run(
            ["docker", "volume", "ls", "-q"],
            capture_output=True,
            text=True,
            timeout=30,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    if result.returncode != 0:
        return False
    return any(name.endswith("neo4j-data") for name in result.stdout.split())


def ensure_env_file(directory: Path, frontend_port: int) -> Path:
    """Create '.env' in *directory* when missing and return its path.

    An existing file is never modified.  The Neo4j password is random on a
    clean install and falls back to the documented default when an existing
    'neo4j-data' volume is detected.
    """
    env_path = directory / ".env"
    if env_path.exists():
        return env_path
    password = DEFAULT_NEO4J_PASSWORD if neo4j_volume_exists() else secrets.token_urlsafe(16)
    content = (
        "# Generated by `tasker setup` - Docker Compose reads these values for interpolation.\n"
        "# Copy the remaining CLI keys from .env.example if you need them.\n"
        "TASKER_INSTALLED=false\n"
        f"TASKER_NEO4J_PASSWORD={password}\n"
        f"API_PORT={DEFAULT_API_PORT}\n"
        f"FRONTEND_PORT={frontend_port}\n"
    )
    with env_path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    console.print(f"[success]Created {env_path.name} with default setup values.[/success]")
    if password == DEFAULT_NEO4J_PASSWORD:
        console.print("[info]Kept the default Neo4j password: an existing 'neo4j-data' volume was detected.[/info]")
    return env_path


def read_env_value(env_path: Path, key: str) -> str | None:
    """Return the value of *key* in an env file, or None when absent."""
    if not env_path.is_file():
        return None
    for line in env_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        name, _, value = stripped.partition("=")
        if name.strip() == key:
            return value.strip()
    return None


def effective_frontend_port(env_path: Path, requested_port: int) -> int:
    """Resolve the frontend port: an existing '.env' entry wins over the flag."""
    existing = read_env_value(env_path, "FRONTEND_PORT")
    resolved = int(existing) if existing and existing.isdigit() else requested_port
    if resolved != requested_port:
        console.print(
            f"[warning]Existing .env sets FRONTEND_PORT={resolved}; "
            f"using it instead of --port {requested_port}.[/warning]"
        )
    return resolved


def compose_up(compose_file: Path, frontend_port: int, dev: bool) -> None:
    """Run `docker compose up -d` (rebuilding images when *dev* is set)."""
    command = ["docker", "compose", "up", "-d"]
    if dev:
        command.append("--build")
    env = {**os.environ, "FRONTEND_PORT": str(frontend_port)}
    try:
        result = subprocess.run(command, cwd=str(compose_file.parent), env=env)
    except OSError as exc:
        console.print(f"[error]Failed to run Docker Compose: {exc}[/error]")
        raise typer.Exit(code=1) from exc
    if result.returncode != 0:
        console.print("[error]docker compose up failed.[/error]")
        console.print("Review the Docker output above, fix the reported problem and re-run 'tasker setup'.")
        raise typer.Exit(code=1)


def setup_command(
    port: int = typer.Option(
        DEFAULT_FRONTEND_PORT,
        "--port",
        "-p",
        help=f"Frontend port published on the host (default: {DEFAULT_FRONTEND_PORT})",
    ),
    dev: bool = typer.Option(
        False,
        "--dev",
        help="Rebuild local images before starting (development mode)",
    ),
) -> None:
    """Start the Tasker Docker stack and print the Setup Wizard URL."""
    console.print("[info]Setting up the Tasker stack...[/info]")
    check_docker()
    compose_file = find_compose_file()
    if compose_file is None:
        console.print("[error]docker-compose.yml not found.[/error]")
        console.print("Run 'tasker setup' from the SocialSeed Tasker repository (or one of its subdirectories).")
        raise typer.Exit(code=1)
    env_path = ensure_env_file(compose_file.parent, port)
    frontend_port = effective_frontend_port(env_path, port)
    console.print("[info]Starting services with Docker Compose...[/info]")
    compose_up(compose_file, frontend_port, dev)
    url = f"http://localhost:{frontend_port}/setup"
    console.print(Panel(f"[bold green]{url}[/bold green]", title="Setup Wizard"))
    console.print("[success]Tasker services started.[/success]")
    console.print(f"Complete the first-run configuration at [bold]{url}[/bold].")
